### ISSUE TITLE
3 Issues

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#1]
First of all, when installed, when I click on a folder, the darkened overlay you get anytime you click on an icon is slightly mispositioned. While it's not a huge issue, a tweak focused on aesthetics probably shouldn't have an issue like that.

![image](https://cloud.githubusercontent.com/assets/9152032/9111447/3e7cf6ca-3c15-11e5-8d33-27e8b8fb9e26.jpg)

Second, mixing and matching themes is challenging, because (as far as I can tell) there is no way to set one theme above the other. For example, my setup uses the themes indigo and enkel. If I wanted enkel's icons to take precedence over indigo's, I don't know how/if I could do that. I wish there was a way to move individual theme parts or even just entire themes up and down in the list to decide which icons to use if the same icon is present in both themes.

Third, (and this one is really not a big deal) the splash screen/ loading screen of the app is pixelated on my iPhone 6. I don't know if it's because of my device's larger screen, or because there is something wrong with the image(s). Regardless, it looks out of place and quite frankly, somewhat ugly in its pixelated state.

![image](https://cloud.githubusercontent.com/assets/9152032/9111454/46d6a668-3c15-11e5-8bfa-86dd238efa80.jpg)

**Comment by coolstar** [comment]
Rearranging the ordering of entire themes has been added in Nightly 264.

Folder icon overlay issue has been fixed in Nightly 267.

**Comment by cj81499** [comment]
Perfect! Any update on the pixelated launch image?

**Comment by coolstar** [comment]
@cj81499 I've talked to the designer and we're getting a brand new launch animation soon, so not much point in re-rendering the current one :)

**Comment by cj81499** [comment]
I think this can be closed because the two glitches with the program have been fixed and the other visual issue is being changed.
