### ISSUE TITLE
Control Center Slider

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#10]
ControlCenterSliderThumb@2x.png (And I assume @1x and @3x also, but I don't have devices to test on) has no impact on the control center slider.

**Comment by coolstar** [comment]
where are you placing this image?

**Comment by cj81499** [comment]
For Veexillum,

/Themes/Veexillum - CC.theme/Bundles/com.apple.MediaPlayerUi/ControlCenterSliderThumb@2x.png

**Comment by cj81499** [comment]
its also in

/Themes/Veexillum - CC.theme/Folders/SpringBoardUI.framework/ControlCenterSliderThumb@2x.png

**Comment by coolstar** [comment]
Pretty sure it's com.apple.MediaPlayerUI and not com.apple.MediaPlayerUi. Paths are case sensitive

**Comment by cj81499** [comment]
Sorry. That's a typo. I have it done correctly.

**Comment by cj81499** [comment]
Any update?

**Comment by coolstar** [comment]
Is this issue still there on the latest version?

Also the correct path is 

/Themes/Veexillum - CC.theme/Bundles/com.apple.SpringBoardUIFramework/ControlCenterSliderThumb@2x.png

**Comment by cj81499** [comment]
That kinda works. The image is placed behind the white line

Image:

![image](https://cloud.githubusercontent.com/assets/9152032/10868831/ffe363c0-8068-11e5-81e3-6170d26f5a71.jpg)

Should all CC images go in com.apple.SpringBoardUIFramework now? If not, what should go there, and where should other things go?

**Comment by coolstar** [comment]
These are the images that should go in there. (You can check yourself using this terminal command).

Use @2x/@3x as required.

```
CoolStars-iPhone-6:~ mobile$ cardump --list /System/Library/PrivateFrameworks/SpringBoardUI.framework/Assets.car
Car-Dump Version 1.0 for ThemeLib
© 2014, CoolStar. All Rights Reserved
Listing contents of car file with name: Assets
Bundle Path: /System/Library/PrivateFrameworks/SpringBoardUI.framework

ControlCenterSliderThumb
ControlCenterSliderTrack

CoolStars-iPhone-6:~ mobile$
```

**Comment by cj81499** [comment]
Ok. That makes sense. Where do the other CC images go? The wiki could use a Control Center page. (Edit: Just made one. I had to leave a lot blank, but if you can fill it out, that would be great)

Do you see what I mean about the white line being above the image? I can post another image if it's not clear to see.

**Comment by cj81499** [comment]
Was the issue where the slider is above the image fixed?

**Comment by coolstar** [comment]
Not sure if there's anything that can really be done on Anemone's end regarding that. iOS renders the control center sliders. Anemone just replaces the images as they're loaded from the car file.

**Comment by cj81499** [comment]
Darn. Okay. Thanks anyways.
