### ISSUE TITLE
Add support for share sheet icons in IconBundles

### ISSUE THREAD

**Issue by maaya1989** [AnemoneTeam/Anemone#100]
![img_0039](https://cloud.githubusercontent.com/assets/13052129/17260341/14ab1568-55d0-11e6-92c0-b14203e606f3.jpg)

I love the idea that you're forcing people to abandon the old bundle way, but did you realize some part of the ui can only be themed with bundles... see the screenshot, it can't be themed with icon bundles so i created some bundles simply to have them themed and voila... the images are totally transparent fyi.

**Comment by coolstar** [comment]
We are working on making IconBundles support theming the share sheet. Also, Bundles is only deprecated for home screen app icons. We still support using them elsewhere to theme the UI.

**Comment by coolstar** [comment]
This has been added in build 352: https://github.com/AnemoneTeam/Anemone/wiki/Share-Sheet-Icons
