### ISSUE TITLE
Calendar not displaying correctly?

### ISSUE THREAD

**Issue by OS-Void** [AnemoneTeam/Anemone#101]
I'm using a theme called Muze 2, and the calendar is only showing the numbers on it but not the image the calendar it's supposed to have, I believe it was working on iOS 8.x, but I'm not too sure. This works fine on WB though.

**Comment by coolstar** [comment]
Anemone uses a different Calendar syntax than WinterBoard. The theme needs to be updated for Anemone.

If this worked with an earlier version of Anemone/iOS however, then it's worth looking at.
