### ISSUE TITLE
Drop support for using Bundles/ and Folders/ to theme home screen Icons

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#103]
Anemone 2.0 should not support using Bundles/ and Folders/ directly to theme home screen icons anymore
# About the legacy method

The legacy method existed prior to Anemone. It requires themers to keep in account the Bundle ID of the app AND the respective icon filename in the app.

This used to work well alongside IconBundles (other than being a PITA for themers) until iOS 9.0.2
# Why we can't use Bundles/Folders for home screen icons anymore

In iOS 9.2-9.3, Apple has implemented caching more aggressively for home screen icons, which breaks the legacy method due to its low level hook. This cache can be cleared but takes 15 seconds to clear on an iPhone 6 and probably takes longer on older devices. This is too long, especially when IconBundles' high level hook works fine without clearing this cache.
# What if I use Bundles/Folders for things other than home screen icons?

Bundles/Folders will still be supported for things like Settings icons, assets found in an "Assets.car" file, or other UI assets. Support is only being dropped for using Bundles for home screen icons.
# How do I switch to IconBundles?

Simply create an IconBundles/ folder in your theme. You can place a 180px x 180px icon named (bundle id)-large.png and Anemone will auto-scale it for all devices. If you don't want auto-scaling, you may use (bundle id)@2x.png or any of the other normal extensions (@3x, ~ipad) and IconBundles will work without automatically scaling it.
# What about older themes?

For older themes that use Bundles/ or Folders/ to theme home screen icons, we convert them to IconBundles automatically as part of Optitheme.

**Comment by coolstar** [comment]
Here's an example of a theme that is ready for these changes and will not break in any way even if we were to not have any form of backwards compatibility: https://github.com/glasklart/hd

We recommend themers check out Glasklart's structure as an example of how it should be. Another good theme to see as an example is Amury (albeit it's paid).

If there's any questions, feel free to ask them here.

**Comment by coolstar** [comment]
I have successfully created a build of Anemone here that has Bundles/Folders theming for app icons disabled, but has Bundles/Folders fully functional for everything else (like app UI). Next up is conversion of Bundles -> IconBundles automatically by Optitheme.

**Comment by Tupring** [comment]
I've been meaning to convert my old icons to the new way for a while now. i really hate having to constantly rename them. I'd like to hear more about the conversion, how it will be done automatically and such. About the long loading times to clear the cache, I also have an iPhone 6S and even just updating Anemone lately sometimes take about five minutes to clear the image caches…

**Comment by coolstar** [comment]
Optitheme is now capable of converting legacy Bundles' app icons to a flattened "legacy support" IconBundles theme automatically. This conversion is not lossless. Automatic conversion grabs the largest possible icon for each app and uses it to create an IconBundles theme that uses "-large".

Optitheme, however, can only know the icon to grab if it is currently described by the app plist or is some well defined "legacy support" file names, so this automatic conversion will not magically make an iOS 7 legacy theme work on iOS 9 or make an iOS 9 legacy theme work on iOS 7. However, it will make an iOS 9 legacy theme work on iOS 9 as an IconBundles theme.

**Comment by coolstar** [comment]
This has been implemented in build 355.

**Comment by Tupring** [comment]
How well will size 128x128 work for the conversion? Will I be better off just using IconBundles and convert myself?

**Comment by coolstar** [comment]
@Tupring 128x128 will work although ideally you'd want 180x180 minimum for iPhone 6+/6s+ support

**Comment by Tupring** [comment]
Thank you! I'm using a 6S.

**Comment by coolstar** [comment]
Build 356 fixes issues with Bundles->IconBundles conversion and adds support for Folders -> IconBundles conversion

**Comment by coolstar** [comment]
This has been fully implemented and is working in the nightlies.
