### ISSUE TITLE
Kills safari video functionality

### ISSUE THREAD

**Issue by badgero1234** [AnemoneTeam/Anemone#107]
This disables something that affects the playability of safari. If you go to kisscartoon.me and load a video the play button never appears. At least that is what happens to me.

**Comment by coolstar** [comment]
Don't get the issue here. Have tried multiple sites over the last few months and haven't seen this issue at all on any of my devices.

**Comment by cj81499** [comment]
@badgero1234 Assuming this is still happening, use iCleaner to disable tweaks until you find what's causing it.
