### ISSUE TITLE
BytaFont Tweak Mode crashes Optitheme daemon. Make Anemone 2.0 uninstall BytaFont Tweak Mode.

### ISSUE THREAD

**Issue by nghiaagent** [AnemoneTeam/Anemone#109]
Shows up whenever Anemone starts up. This error causes theme to not properly load, overlap each other, doesn't take effect,.. etc. reinstalling tweaks doesn't help at all. Are there any fix to this?

**Comment by Iormangund** [comment]
Having the same problem. I managed to get rid of it after clearing cydia sources, uninstalling all anemone tweaks, disabling all tweaks, rebooting, respringing and using icleaner. All multiple times.
Finally got it to not come up with that error, and now it's started doing it again and frozen the active anemone tweaks in place. I tried this in default cydia repo (345) and on anemone nightly build repo (356), same result.

I managed to at least clear the uninstalled theme elements that kept getting reapplied everytime I reinstalled anemone by deleting the anemonecache in /var/stash. However, anemone still gives the optitheme error no matter how much I uninstall, reboot and clean everything.

**Comment by Iormangund** [comment]
I have tried remove anemone, pinch and rocketbootstrap, use icleaner and manually remove any anemone/rocketbootstrap files via ifile (preferences, caches etc). Reinstall anemone and it's dependancies, still daemon error.
I have also tried unloading and loading optitheme and rocketbootstrap daemons maually via terminal, no success. Running out of ideas on what to try, short of re-jailbreaking which I do not want to do.

**Comment by coolstar** [comment]
Have you tried Rebooting the device (and running the Pangu app if needed)?

**Comment by Iormangund** [comment]
Yes, multiple times between uninstalls, and reinstalls. Have done 2-3 respring between each attempt aswell.

**Comment by Iormangund** [comment]
Ok, so an update. Managed to get anemone to work again by completely removing cydia substrate and substrate safe mode, using icleaner then reinstalling it all. However, after the very first time applying theme settings it now is coming up with the daemon error.

**Comment by Iormangund** [comment]
Last update, seems the issue could be caused by specific themes or icon themes in general, don't remember what the initial themes were when i first installed the app yesterday but on the last failed tests (must have done 30+ reboots/uninstall/reinstalls today, all fails) the daemon failed as soon as i installed fl4t1os8. 

So far however I haven't installed any themes other than wifidots and flipcontrolcenter and the daemon hasn't crashed. Giving up on themes for now as it's far too much effort reinstalling every tweak after removing substrate every time the daemon crashes.  Also, whatever it's doing it also stops protect my privacy from working.

Edit: Seems I was wrong, isn't just theme related. With no apparent cause the error started happening again today, I didn't change anything in anemone since yesterday, just opened it to check what settings I had enabled.

**Comment by banananutpie96** [comment]
I'm having this issue too. Nothing I've done has fixed it. Maybe it's because of the update to iOS? I haven't updated (still on 9.3.3) but this started around the same time as the update came out. That can't be a coincidence.

**Comment by coolstar** [comment]
If you go to Settings > Privacy > Diagnostics and Usage > Diagnostics and Usage Data, do you see any entries with "AnemoneOptimizer" in it?

**Comment by banananutpie96** [comment]
All mine has is a bunch of listing of "JetsamEvent"

**Comment by Iormangund** [comment]
also have a lot of JetsamEvent entries. Here is what the first one says about AnemoneOptimizer:

 {
    "rpages" : 402,
    "states" : [
      "daemon",
      "idle"
    ],
    "name" : "AnemoneOptimizer",
    "pid" : 1182,
    "reason" : "per-process-limit",
    "fds" : 50,
    "uuid" : "(Removed as I didn't know if it was a privacy risk)",
    "purgeable" : 0,
    "cpuTime" : 0.050009,
    "lifetimeMax" : 1435
  },

**Comment by maaya1989** [comment]
Same here, has tried every possible way to fix it but the error always comes back...

several posts on reddit already, please figure out a fix soon...
https://www.reddit.com/r/iOSthemes/comments/4v4l83/question_anemone_keeps_giving_me_an_error_saying/
https://www.reddit.com/r/iOSthemes/comments/4we9t2/question_there_was_an_error_contacting_the/

(tried the hard reboot too but not working...)

**Comment by maaya1989** [comment]
Ok everyone I think I found the conflict, it's bytafont, I'm using tweak mode and as soon as I disable it, the error is gone. Coolstar can you check it? I've emailed bytafont too to see if it's on their end.

**Comment by Iormangund** [comment]
Wow, nice catch, just tested that on my phone (6s) and ipad (air1) on 9.3.3. Uninstalling byta font tweak mode let anemone communicate with the daemon again. Also fits in with why removing substrate worked for me before, tweak mode was autoremoved along with substrate while the main byta font wasn't, didn't register that at the time so didn't consider byta font to be involved therefore thought nothing of it when re-enabling my fonts.

**Comment by coolstar** [comment]
This is really surprising as the Optitheme daemon doesn't deal with fonts at all...

Wonder what bytafont tweak mode is up to that is causing it to crash Optitheme.....

Can someone replicate this on an iOS 9.0.2 or 9.1 device and get a crash report from CrashReporter on Cydia?

**Comment by Iormangund** [comment]
Unfortunately I only have 9.3.3 devices now. I did retest protect my privacy and that works fine now byta font tweak mode is uninstalled. Swap mode works without issue with byta too. Thinking the issue might be with byta font tweak mode itself and have nothing to do with anemone.

**Comment by mwoolweaver** [comment]
@maaya1989 might I suggest using Anemone to change your font? You can find a few fonts that you can use with Anemone @ https://mwoolweaver.github.io and I will also try my best to fill any request you may have

**Comment by coolstar** [comment]
Anemone 1.1-371 now conflicts with Bytafont's "Tweak Mode" to resolve this issue.
