### ISSUE TITLE
How to overlap themes?

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#11]
https://www.reddit.com/r/iOSthemes/comments/3ietzs/question_how_to_overlap_themes_in_anemone/

**Comment by coolstar** [comment]
This can already be done. Just tap edit with no theme expanded and you can rearrange entire themes themselves.

**Comment by cj81499** [comment]
@coolstar You misunderstood. I know that you can reorder themes. I mean overlap. As in move one part of a theme above a part of another theme.

**Comment by cj81499** [comment]
After looking at the reddit post again, it seems I misunderstood the poster, however, I'm still wondering if my question is possible.

**Comment by cj81499** [comment]
@coolstar, not to nag, but I'm still curious.
