### ISSUE TITLE
Changing icons in notification banners 

### ISSUE THREAD

**Issue by hodgesh3** [AnemoneTeam/Anemone#113]
So I have applied a theme through anemone, which works perfectly well. However I would like to modify the theme so that banner notifications use the stock iOS icons instead of the theme's. I know winterboard allows this by moving/renaming/overwriting icons in the bundle folders. How would I be able to do this with anemone?

**Comment by coolstar** [comment]
One of Anemone's core features with IconBundles is that themers only have to worry about putting 1 icon to have it theme not only home screen icons, but also the share sheet, notifications and spotlight.

This request is contrary to one of Anemone's core values and so will not be fulfilled.
