### ISSUE TITLE
Add Proper support for iPad Air 2 upscaled to Pro res & iPad Pro

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#114]
Currently when using Anemone on an upscaled iPad Air 2 to iPad Pro resolution, the icon masks, overlays and shadows aren't implemented correctly. This is because at the Air 2's resolution it should be reading AppIconMask-RFB@2x~ipad.png instead of AppIconMask@2x~ipad.png.

Also need to add support for themes to add an icon via Anemone that isn't originally on the filesystem to fix the icon mask issue with the Air 2 upscaled to the iPad Pro res.

iPad Pro Checklist:
- [X] Add support for theming icons not originally on the filesystem
- [X] Fix IconBundles -large sizing
- [X] Fix size of dock reflections
- [x] Fix Clock Icon Mask
- [x] Add separate Shadows & Overlays images

**Comment by coolstar** [comment]
Also the dock reflection height appears to be incorrect with the Air 2 upscaled to the iPad Pro resolution. This will also need to be fixed.

**Comment by coolstar** [comment]
Anemone can now load themed versions of icons that aren't originally on the filesystem, sorting out issues with most icons on an iPad Air 2 upscaled to the iPad Pro screen res.

**Comment by coolstar** [comment]
Dock Reflection Height is now fixed for iPad Pro

**Comment by dreamnet** [comment]
@coolstar Sound great! Any thoughts about supporting universal themes for iPad (Pro), iPhone, iPod... using -large icons? Could be made with sections for different devices in the `Info.plist`... ?

**Comment by coolstar** [comment]
@dreamnet -large already works with supporting iPhone, iPod and iPad. I'll be looking if there's any issues with the iPad Pro and fixing them

**Comment by coolstar** [comment]
Fixed the Clock icon mask on the Air 2 upscaled to the iPad Pro res by bringing over the sizes used in IconBundles -large rather than assuming the clock icon on disk is the correct size.

**Comment by coolstar** [comment]
Added "iPadPro" shadows, underlays and overlays. Fallback to iPad on iPad Pro if iPadPro isn't available

**Comment by coolstar** [comment]
These additions have all been implemented in 1.1-365
