### ISSUE TITLE
Theme Icon pictures not changing

### ISSUE THREAD

**Issue by jerpatran** [AnemoneTeam/Anemone#116]
Theme pictures not chaneing on home screen. The icon shapes change and some I one pictures change in files and also on Berry C8. I have a iPhone 6s running iOS 9.3.3, and its jailbronke.

**Comment by coolstar** [comment]
Is this on the BigBoss version or the latest nightly?

**Comment by jerpatran** [comment]
Version 1.1-366, Is this what your looking for?
Jerry

Sent from my iPhone
JPR

**Comment by coolstar** [comment]
Which theme do you have installed?

**Comment by jerpatran** [comment]
Blur, Annabelle, and Aurora 

Sent from my iPhone
JPR

**Comment by jerpatran** [comment]
I believe my issue was a tweak conflict with Anemone.  I'm not sure what tweak was creating the conflict but I think it was Depthicons.
