### ISSUE TITLE
Control center icons

### ISSUE THREAD

**Issue by tdmd** [AnemoneTeam/Anemone#119]
Control center icons.  perhaps because of the move to IconBundles, there may have been a bug introduced.  the  ControlCenterGlyphCamera@2x.png is not showing up in the control center.   The airplane mode, wifi, bluetooth, DND, and orientation lock do work though.

**Comment by coolstar** [comment]
This is not due to the move to IconBundles. It's probably just that Apple changed the file names in iOS 9.3.x. Bundles are still used for control center icons.
