### ISSUE TITLE
FolderIcon doesnt work

### ISSUE THREAD

**Issue by stack-alchemy** [AnemoneTeam/Anemone#12]
Hey just try the folder icon feature. it is shown while applying in anemone but there is no folder icon on springboard after it. any idea how to fix this?

**Comment by Big-Jellyfish** [comment]
in addition with anemone there is no folder background tweak working anymore. folder icon customizing seems to be switched off. when I use Winterboard again it is working.

only icon overlay is working (also for folders) but I want the folders to be different

**Comment by coolstar** [comment]
The folder icon feature is known to be working. Please check your implementation against Glasklart, which has a working folder icon theme.
