### ISSUE TITLE
Small bug in share sheet

### ISSUE THREAD

**Issue by maaya1989** [AnemoneTeam/Anemone#121]
Look at the iCloud Photo Sharing icon, tired both old bundle way and icon bundle way. Strangely bundle way kinda worked, just effects weren't implied, icon bundle didn't theme it at all, which was fine in old betas... It's broken since last two betas.
![img_0047](https://cloud.githubusercontent.com/assets/13052129/17644764/df9a4756-618f-11e6-88d5-6a11327218b6.jpg)
![img_0045](https://cloud.githubusercontent.com/assets/13052129/17644765/dfbcc790-618f-11e6-9524-cd08ad6ac038.jpg)

**Comment by coolstar** [comment]
Does this issue still happen on the latest nightly?

**Comment by dreamnet** [comment]
@coolstar Yes, screenshot using nightly -375:
![img_0452](https://cloud.githubusercontent.com/assets/2068130/17833239/a124f5f6-6717-11e6-923c-459568750160.PNG)
180x180px `PLActivityTypeAlbumStream-large.png` is in the theme.

**Comment by coolstar** [comment]
Fixed in 1.1-388

**Comment by dreamnet** [comment]
@coolstar Jep, seems to be fine with 1.1-388. :+1:
