### ISSUE TITLE
Suggestion for new checkboxes in the Anemone UI

### ISSUE THREAD

**Issue by dreamnet** [AnemoneTeam/Anemone#122]
@coolstar I don't know if I'm the only one who don't like the checkboxes in the Anemone user interface... and there seems to be a bug with them... they are changing size when first selecting/deselecting a theme.
Here are two - maybe - nicer suggestions for them:

| Checkboxes | Selected | Unselected |
| --- | --- | --- |
| Version 1 | ![selected_1](https://cloud.githubusercontent.com/assets/2068130/17648692/f07736f8-621e-11e6-8906-e1b4e18de416.png) | ![unselected](https://cloud.githubusercontent.com/assets/2068130/17648694/fe46594e-621e-11e6-8f80-5c2353da2a53.png) |
| Version 2 | ![selected_2](https://cloud.githubusercontent.com/assets/2068130/17648744/16b15252-6221-11e6-9f73-18f9103d4018.png) | ![unselected](https://cloud.githubusercontent.com/assets/2068130/17648699/0d902894-621f-11e6-8d67-f31b6e5225b9.png) |

Version 2 is a bit more "serious" :grin: and better to see than Version 1.
The images above are made by me - you can use them for Anemone if you want.

**Comment by enaloha** [comment]
Version 1 is quite pretty. I themed the app and they look great. Surprisingly, I had to move the images into the app bundle. For some reason, placing them into ThemeName/Bundles/com.anemonetheming.anemone did not theme them. Would that count as a bug?

**Comment by coolstar** [comment]
I have opted to use a slight variant of "Version 2", color matched to the existing enable/disable buttons.

| Checkboxes | Selected | Unselected |
| --- | --- | --- |
| Official | ![selected](https://cloud.githubusercontent.com/assets/1431548/17830256/b606eeee-667b-11e6-9828-f1f3a5d2deba.png) | ![unselected](https://cloud.githubusercontent.com/assets/1431548/17830257/be05e82a-667b-11e6-881e-14a3799dd21a.png) |

These are the official images used in 1.1-375
