### ISSUE TITLE
Unresponsive Safari with breadcrumb on status bar and video opened

### ISSUE THREAD

**Issue by jluo98** [AnemoneTeam/Anemone#123]
When open a link from an app, Safari launches with a breadcrumb on status bar saying back to <name of app>. 
Under this condition, if I start playing a html 5 video on any webpage, Safari would be unresponsive.
After disabling my current theme, the problem persists. But disabling Anemone Cydia substrates in iCleaner Pro fixes this issue. 
This bug is not present if there is no breadcrumb on status bar (normal signal & carrier indicator).

Anemone Version: 1.1-345
iOS Version: 9.3.3
Phone Model: iPhone 6s Plus, 64 GB
PS: I do not have any tweak installed for breadcrumb (e.g. BreadcrumbsAway)

**Comment by coolstar** [comment]
Can you try on the latest nightly build and see if this problem is still there?

**Comment by jluo98** [comment]
I just tried, the problem persists unfortunately. 
I have BreadcrumbsAway installed, after I dismiss the breadcrum, video works fine. I guess this is a temporary solution for it.

**Comment by coolstar** [comment]
Just tested on Anemone 1.1-406. Opened Safari from link in Tweetbot, then opened Youtube video in Safari with the breadcrumb. No issues with video playback here.

Tested on: iPhone 6, 64 GB iOS 9.3.3. Anemone 1.1-406.

**Comment by coolstar** [comment]
![image](https://cloud.githubusercontent.com/assets/1431548/18104445/f71d81d6-6eaf-11e6-8bfa-7d977e5345fd.png)
![image](https://cloud.githubusercontent.com/assets/1431548/18104446/f7222e02-6eaf-11e6-8742-dacf45485e73.png)

**Comment by jluo98** [comment]
Cool. Thanks for the update!
