### ISSUE TITLE
DRM

### ISSUE THREAD

**Issue by pdobq** [AnemoneTeam/Anemone#125]
Hello,

I wish to suggest a new option for Anemone. The ability to create a DRM check by specifying a URL in the .plist file.

Have a good day'

**Comment by goeo-** [comment]
drm is useless. a standardized one, even more. a three line crack could crack all themes if this was done.

**Comment by coolstar** [comment]
DRM for themes is not practical. Even in the best case scenario where the DRM were effective, what's to stop pirates from extracting the images by taking a screenshot?

Or even if screenshots are stopped, they could still clean the display and use a high resolution camera to take a picture of the screen and extract the icons and elements from there.

**Comment by pdobq** [comment]
At least it should slow down piracy... But, no prob'
