### ISSUE TITLE
Crashes my springboard 

### ISSUE THREAD

**Issue by Minix105** [AnemoneTeam/Anemone#126]
Every time I put my phone in sleep mode it goes to safe mode and says springboard crashed and i know it was Anemone because when I deleted it it worked fine I hope you can help me because I want to use this tweak real bad and in on an iPhone 6s Plus if you need to know and thx hope you can fix this

**Comment by Minix105** [comment]
Sry for the type o meant to say I'm

**Comment by coolstar** [comment]
Duplicate of #110

**Comment by shawn954** [comment]
Yeah I'm having the same problem. It really sucks cause this the only theme app they got for using themes and it isn't working right.

**Comment by coolstar** [comment]
Please don't make any additional comments here. The issue is being tracked at #110
