### ISSUE TITLE
Icon Overlay only works for Bundles and not for IconBundles

### ISSUE THREAD

**Issue by stack-alchemy** [AnemoneTeam/Anemone#13]

**Comment by coolstar** [comment]
Icon Overlay works fine on both. You probably have IconBundles (the separate tweak) installed. That tweak is no longer needed as Anemone has IconBundles functionality built in.

**Comment by Big-Jellyfish** [comment]
hey thanks for reply.

indeed i had installed icon bundles. but i just uninstalled and it has no effect.

any other idea?

Mit freundlichen Grüßen
Jörg Witthaus

**Comment by cj81499** [comment]
@coolstar, maybe you missed it, but@iamable is still having issues with this.

**Comment by cj81499** [comment]
Oops @iamable

**Comment by Big-Jellyfish** [comment]
my biggest problem is Overlay for folders doesnt work. with winterboard it works

**Comment by cj81499** [comment]
You could try using this to achieve a similar look to what you want (maybe) https://github.com/AnemoneTeam/Anemone/wiki/Folder-Icons

**Comment by Big-Jellyfish** [comment]
Thank you I know that wiki page. I tried that several times, but it doesnt work. anemone show it correctly while pressing apply but it doesnt appear after respring

Mit freundlichen Grüßen
Jörg Witthaus

**Comment by cj81499** [comment]
"You can see https://github.com/glasklart/hd as an example of a theme that uses folder icon backgrounds."

From [this thread](https://github.com/AnemoneTeam/Anemone/issues/4). Maybe that will help.

**Comment by Big-Jellyfish** [comment]
Thank you. found something out.
folder overlay works with every theme but not with rome theme.
also the Glasklart Folder theme doesnt work together with rome.
Any idea why?

**Comment by cj81499** [comment]
@iamable I have no clue. Maybe @coolstar knows?

**Comment by Big-Jellyfish** [comment]
oh finally you fixed that problem. although you stopped supporting me thank you for your work on anemone.

best regards
