### ISSUE TITLE
dock not changing

### ISSUE THREAD

**Issue by urmishr** [AnemoneTeam/Anemone#130]
as title says dock background not changing with the latest vesrsion.

**Comment by mwoolweaver** [comment]
is there an entry for [DockMode](https://github.com/AnemoneTeam/Anemone/wiki/Dock) in the theme you are using?

**Comment by urmishr** [comment]
ya, I am using ambre ios 9.It has many docs. I tried all of them but dock
not changing at all.I even tried different themes but no lock.

**Comment by mwoolweaver** [comment]
I use that same theme and I had to fix it myself...

Just add https://mwoolweaver.github.io/Public-Repo and install the Classic Dock fix and see what happens after you enable it in Anemone...

**Comment by urmishr** [comment]
let me try

**Comment by urmishr** [comment]
working great man,thanks
