### ISSUE TITLE
Bytafont Tweak

### ISSUE THREAD

**Issue by marty526** [AnemoneTeam/Anemone#131]
Is there going to be an update to allow both Anemone and Bytafont Tweak? I had both working perfectly fine up until the last update and now I can't use my fonts I created

**Comment by coolstar** [comment]
No. BytaFont Tweak Mode causes problems and will not be removed from the conflicts list.

**Comment by mwoolweaver** [comment]
Might i suggest using Anemone to change your font? You can go to https://mwoolweaver.github.io/Anemone-Fonts and it'll tell you what you need...
