### ISSUE TITLE
Start deprecating legacy WinterBoard themes

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#133]
Mark legacy WinterBoard themes with a different (preferably ugly) color to encourage themers to add Anemone in their control file properly rather than marking their theme as compatible with WinterBoard.

**Comment by coolstar** [comment]
Implemented in 1.1-377

**Comment by mwoolweaver** [comment]
so what is the standard by which themes are judged for this qualification?

**Comment by coolstar** [comment]
If the theme was installed from a debian package or from Cydia and has "Depends: winterboard".

If a theme is deprecated, it is highlighted in red and a warning will show up if it's applied.

**Comment by mwoolweaver** [comment]
What if a theme also has com.anemonetheming.anemone as well as winterboard as a dependency? 

![img_0431](https://cloud.githubusercontent.com/assets/5729320/17876030/9cf7cd1a-689c-11e6-8289-14aa0f530b4a.PNG)

**Comment by coolstar** [comment]
if both are listed, anemone needs to be listed first to not be treated as legacy

**Comment by coolstar** [comment]
1.1-390 changes the "red coloring" to a "warning emoji" to make the theme list less ugly

**Comment by coolstar** [comment]
A suggestion that was received: After checking control file, if a theme uses IconBundles with "-large", do not mark the theme as legacy regardless of what the control file said.
