### ISSUE TITLE
Anemone fonts issue with Skype

### ISSUE THREAD

**Issue by hoangthanh2408** [AnemoneTeam/Anemone#135]
Can't apply Anemone fonts for Skype application.
Please take a look at this issue & update Anemone fonts support full apps
Many thanks guys!

**Comment by mwoolweaver** [comment]
could you provide info about what device and iOS version you are using?

**Comment by coolstar** [comment]
Skype does not use the "San Francisco" system font. The font package will need to support theming the font that Skype uses. (It looks like it's using its built-in Segoe UI Font)
