### ISSUE TITLE
Missing App Store Share Sheet icons

### ISSUE THREAD

**Issue by dreamnet** [AnemoneTeam/Anemone#137]
When opening App Store, selecting a **paid app** and opening the share sheet, there are two missing icons:
- Add to Wish List (`ShareSheetWishList@2x.png` btw `ShareSheetWishList@3x.png`) and
- Gift (`ShareSheetGift@2x.png` btw `ShareSheetGift@3x.png`)

Both images are located in `/System/Library/PrivateFrameworks/StoreKitUI.framework/Assets.car`.
Screeny:
![img_0453](https://cloud.githubusercontent.com/assets/2068130/17957823/229ff66e-6a95-11e6-986d-1ab7d4d57310.PNG)
Please ad these two images also to [the WIKI](https://github.com/AnemoneTeam/Anemone/wiki/Share-Sheet-Icons).

**Comment by coolstar** [comment]
These are the IDs for those icons:

SKUIActivityTypeWishlist
SKUIActivityTypeGift

**Comment by coolstar** [comment]
I have updated the wiki.

**Comment by dreamnet** [comment]
@coolstar Thank you very much! :+1:
