### ISSUE TITLE
ANEMFolderBackground@2x.png crashes phone to safe mode upon folder icon tap

### ISSUE THREAD

**Issue by Alfroggy** [AnemoneTeam/Anemone#138]
Crash and sys-logs :+1: https://www.dropbox.com/sh/5tipm9v5nc8lh5r/AABxKQ4-_eB5-tG0aZsbFzhWa?dl=0

**Comment by coolstar** [comment]
Looks like a problem with Xen, not Anemone.

**Comment by Matchstic** [comment]
This certainly does not look like an issue in Xen. There's nothing from my tweak in the stack trace, and what's being logged happens typically a couple of seconds after the device finishes unlocking.

**Comment by coolstar** [comment]
Confirmed no crash here with ANEMFolderBackground@2x.png on iPhone 6, 9.3.3 with only Anemone and no Xen installed.

**Comment by Matchstic** [comment]
@Alfroggy , can you let me know what theme you're using that is producing this issue? I'm going to check it this end.

**Comment by Alfroggy** [comment]
It's Jaku which I'm porting to Anemone.

**Comment by Alfroggy** [comment]
Happens without Xen installed too.

@coolstar :
https://www.dropbox.com/sh/m0wpoe8iovtk1go/AAAMcN3vAAXJSRHO21QVR0AIa?dl=0

**Comment by Alfroggy** [comment]
With Xen again :

https://www.dropbox.com/sh/8jvvwq99lmaf6vq/AAAs-4zdC9JXfZqHw6qED0Kda?dl=0

**Comment by coolstar** [comment]
@Alfroggy can you download Glasklart from here: https://github.com/glasklart/hd and test?

Enable "Glasklart Folders" and see if it crashes with that theme.

**Comment by Alfroggy** [comment]
Installing...
![image](https://cloud.githubusercontent.com/assets/13683006/17988417/72a5d4e4-6b26-11e6-8e47-117be6585bbf.png)
