### ISSUE TITLE
Theme Categorization Page should have an example .plist

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#14]
I'm not sure how to add the info to my theme without an example.

**Comment by coolstar** [comment]
These are simple strings that are added to the plist.

**Comment by cj81499** [comment]
Adding an example would be helpful. I don't know how to add the string. Different strings work in different ways and since you have examples for many other pages, it makes sense to have one for the Theme Categorization page too.

**Comment by mwoolweaver** [comment]
Would this be the kind of example you are looking for?

https://github.com/Anemone-Fonts/Example_Anemone_Font/blob/master/raw/Example_Anemone_Font/Library/Themes/Example%20Anemone%20Font.theme/Info.plist

and you just swap "Fonts" for what ever category you are using (examples below from the wiki page):
- Docks
- Badges
- Overlays
- Masks
- System Colors
- Icons

**Comment by cj81499** [comment]
@mwoolweaver yeah. That would do it, although I did figure it out by now lol.
