### ISSUE TITLE
Anemone 1.1.-389 breaks shadows on Legacy

### ISSUE THREAD

**Issue by gmawji** [AnemoneTeam/Anemone#140]
Title says it all, had a few people try to confirm. The latest nightly breaks shadows on themes marked as legacy.

Legacy Theme:
https://files.slack.com/files-pri/T0FRMM50W-F25AVRQJZ/no_shadows_here_.jpg

https://files.slack.com/files-pri/T0FRMM50W-F25A4BZ52/slack_for_ios_upload.png

Non-Legacy:
https://files.slack.com/files-pri/T0FRMM50W-F25A69D1A/slack_for_ios_upload.jpg

**Comment by gmawji** [comment]
looks like its the geneous tweak, oddly breaks shadows in only a few themes.
Idk if its an Anemone clash with Geneous or a Geneous clash with Anemone, anyhow im closing this, uninstalling Geneous brings shadows back.

**Comment by coolstar** [comment]
"Legacy" themes are purely cosmetic in the Anemone app. Functionality is not affected when the theme is applied if it's flagged as legacy.
