### ISSUE TITLE
Anemone not properly clearing keybaord cache when applying new font

### ISSUE THREAD

**Issue by mwoolweaver** [AnemoneTeam/Anemone#141]
So i have received a fair amount of reports that Anemone isn't changing the Keyboard font when applying a font. I have narrowed it down to Anemone not clearing the keyboard cache for some reason. To fix this issue I have been instructing people to use iCleaner to clean "Cache Files".

 More evidence below. 

https://twitter.com/f0llows_you/status/769197904275902465 - you see in this discussion the clearing the caches with iCleaner Pro fixes the issue.

https://twitter.com/jaimetorres_85/status/768808293548584960 and again here iCleaner Pro solved the issue.

https://www.reddit.com/r/jailbreak/comments/4zn622/discussion_is_there_a_way_to_change_the_keyboard/d6x88jr?context=3 and again here iCleaner Pro fixed the issue.

**Comment by coolstar** [comment]
Which setting in iCleaner fixes the issue? "Cache Files"? What happens if you run iCleaner without selecting any of the options

**Comment by mwoolweaver** [comment]
yes the "Cahce Files" is all i have been telling people to tap. 

I haven't tested it with cleaning everything

**Comment by coolstar** [comment]
Can you check iCleaner's log and get which files it's clearing with "Cache Files" selected?

**Comment by mwoolweaver** [comment]
sure

**Comment by mwoolweaver** [comment]
here's the list as shown by iCleaner Pro

###################

# PROCESSED FILES

###################

Date: 08-26-2016 13:32

Number of files: 352
Approximate size: 111.22 MiB

Cache files
###########

##
In dir: /var/mobile/Library/Caches
##

./com.apple.keyboards/images

./com.apple.keyboards/images/1102069257260340148210051375082241746589

./com.apple.keyboards/images/1102069257260340148210051375082510182046

./com.apple.keyboards/images/1102069257260340148210057822383284139118

./com.apple.keyboards/images/1102069257260340148210745124644694314837

./com.apple.keyboards/images/1102069257260340148211240002810940777066

./com.apple.keyboards/images/1102069257260340148211240002810940777070

./com.apple.keyboards/images/1102069257260340148211431782456298192526

./com.apple.keyboards/images/1102069257260340148211448459232039132286

./com.apple.keyboards/images/1102069257260340148211448459232039132290

./com.apple.keyboards/images/1102069257260340148211476199295079374034

./com.apple.keyboards/images/1102069257260340148211476199295163260119

./com.apple.keyboards/images/1102069257260340148211981695350551902318

./com.apple.keyboards/images/1102069257260340148211981695350551902322

./com.apple.keyboards/images/1102069257260340148212279718455914037662

./com.apple.keyboards/images/1102069257260340148212348246927385529144

./com.apple.keyboards/images/110206925726034014821253570156243756259

./com.apple.keyboards/images/110206925726034014821253570160538723557

./com.apple.keyboards/images/1102069257260340148212915571479494364278

./com.apple.keyboards/images/1102069257260340148212915571481641847928

./com.apple.keyboards/images/1102069257260340148212920676392867632103

./com.apple.keyboards/images/1102069257260340148212920676393404503017

./com.apple.keyboards/images/1102069257260340148213189671645599486460

./com.apple.keyboards/images/1102069257260340148213189671646136357374

./com.apple.keyboards/images/1102069257260340148213260362792440739768

./com.apple.keyboards/images/1102069257260340148214085295561011854355

./com.apple.keyboards/images/1102069257260340148214766700123601719290

./com.apple.keyboards/images/1102069257260340148214766700123601719355

./com.apple.keyboards/images/1102069257260340148214783740877995356158

./com.apple.keyboards/images/1102069257260340148214783740879069097983

./com.apple.keyboards/images/1102069257260340148214925048324366994930

./com.apple.keyboards/images/1102069257260340148214975022226442807967

./com.apple.keyboards/images/1102069257260340148215062576723978127188

./com.apple.keyboards/images/1102069257260340148215183896899739705504

./com.apple.keyboards/images/1102069257260340148215183896900008140961

./com.apple.keyboards/images/11020692572603401482153707849361604857

./com.apple.keyboards/images/1102069257260340148215441182942465472746

./com.apple.keyboards/images/1102069257260340148215441182943002343660

./com.apple.keyboards/images/1102069257260340148215491717803377109864

./com.apple.keyboards/images/1102069257260340148215491717803444218730

./com.apple.keyboards/images/1102069257260340148215527280279526023226

./com.apple.keyboards/images/1102069257260340148215589598711877948266

./com.apple.keyboards/images/1102069257260340148215589598711945057132

./com.apple.keyboards/images/1102069257260340148215643815811881603413

./com.apple.keyboards/images/1102069257260340148216229040210020188601

./com.apple.keyboards/images/1102069257260340148216278656221980654995

./com.apple.keyboards/images/1102069257260340148216278656221980655004

./com.apple.keyboards/images/110206925726034014821644685074393977455

./com.apple.keyboards/images/110206925726034014821644685074662412913

./com.apple.keyboards/images/1102069257260340148216471735215565179960

./com.apple.keyboards/images/1102069257260340148216471735217712663609

./com.apple.keyboards/images/1102069257260340148216507004218561693672

./com.apple.keyboards/images/1102069257260340148216507004218645579757

./com.apple.keyboards/images/1102069257260340148216549527888899747606

./com.apple.keyboards/images/1102069257260340148216690469164947516717

./com.apple.keyboards/images/1102069257260340148216800128429351571883

./com.apple.keyboards/images/1102069257260340148216800128429351571888

./com.apple.keyboards/images/1102069257260340148217196361299549933364

./com.apple.keyboards/images/1102069257260340148217196361301697417013

./com.apple.keyboards/images/1102069257260340148217233585711992440287

./com.apple.keyboards/images/1102069257260340148217233585716287407585

./com.apple.keyboards/images/1102069257260340148217382766435273492674

./com.apple.keyboards/images/1102069257260340148217460570644835917107

./com.apple.keyboards/images/1102069257260340148217460570645909658933

./com.apple.keyboards/images/1102069257260340148217512004814581358681

./com.apple.keyboards/images/1102069257260340148217512004814581358938

./com.apple.keyboards/images/1102069257260340148217527210149397040322

./com.apple.keyboards/images/1102069257260340148217856287778681628364

./com.apple.keyboards/images/1102069257260340148218037805555834402681

./com.apple.keyboards/images/1102069257260340148218037805556102838139

./com.apple.keyboards/images/1102069257260340148218130518303617831266

./com.apple.keyboards/images/1102069257260340148218130518303617851751

./com.apple.keyboards/images/1102069257260340148218241793332428606619

./com.apple.keyboards/images/1102069257260340148218241793332697042076

./com.apple.keyboards/images/11020692572603401482192953438933447639

./com.apple.keyboards/images/11020692572603401482192953439470318552

./com.apple.keyboards/images/110206925726034014822214515388869385550

./com.apple.keyboards/images/110206925726034014822214515388936494416

./com.apple.keyboards/images/110206925726034014822473309873535729742

./com.apple.keyboards/images/110206925726034014822473309874609471568

./com.apple.keyboards/images/110206925726034014822721384154077851004

./com.apple.keyboards/images/110206925726034014822721384154077851069

./com.apple.keyboards/images/110206925726034014823117657577157059070

./com.apple.keyboards/images/110206925726034014823137053548901593799

./com.apple.keyboards/images/110206925726034014823298074306623369264

./com.apple.keyboards/images/110206925726034014823439197202323157753

./com.apple.keyboards/images/110206925726034014823458787368375810711

./com.apple.keyboards/images/110206925726034014823461541666563483959

./com.apple.keyboards/images/110206925726034014823461541668710967608

./com.apple.keyboards/images/110206925726034014823548261677159853911

./com.apple.keyboards/images/110206925726034014823682729016381961580

./com.apple.keyboards/images/110206925726034014823682729016449070446

./com.apple.keyboards/images/110206925726034014823785366597016685025

./com.apple.keyboards/images/110206925726034014823785366597285120483

./com.apple.keyboards/images/110206925726034014823952237224809108690

./com.apple.keyboards/images/110206925726034014823952237225345979603

./com.apple.keyboards/images/110206925726034014824061513782645782755

./com.apple.keyboards/images/11020692572603401482467694226293801247

./com.apple.keyboards/images/11020692572603401482468843410059184672

./com.apple.keyboards/images/110206925726034014824830498003092463507

./com.apple.keyboards/images/110206925726034014825107169935655283247

./com.apple.keyboards/images/110206925726034014825107169935688837681

./com.apple.keyboards/images/11020692572603401482521843097755145336

./com.apple.keyboards/images/11020692572603401482521843097755165821

./com.apple.keyboards/images/110206925726034014825263186149571673755

./com.apple.keyboards/images/110206925726034014825326987892700937266

./com.apple.keyboards/images/110206925726034014825425084800781211962

./com.apple.keyboards/images/110206925726034014825645081525119080796

./com.apple.keyboards/images/110206925726034014825976568179949580430

./com.apple.keyboards/images/110206925726034014826622508325746307008

./com.apple.keyboards/images/110206925726034014826914826095891147993

./com.apple.keyboards/images/11020692572603401482713634447719998126

./com.apple.keyboards/images/11020692572603401482713634452014965424

./com.apple.keyboards/images/110206925726034014827340351849572594385

./com.apple.keyboards/images/11020692572603401482758136542597900917

./com.apple.keyboards/images/110206925726034014827971969475771636478

./com.apple.keyboards/images/110206925726034014828772041464693832533

./com.apple.keyboards/images/110206925726034014829243794309587142490

./com.apple.keyboards/images/110206925726034014829243794309654251356

./com.apple.keyboards/images/110206925726034014829341675218087980892

./com.apple.keyboards/images/110206925726034014829341675218155089758

./com.apple.keyboards/images/110206925726034014829693463467055552453

./com.apple.keyboards/images/110206925726034014829852791604998079062

./com.apple.keyboards/images/110206925726034014829852791605065187928

./com.apple.keyboards/images/1479594642413384923310769152455872595290

./com.apple.keyboards/images/1479594642413384923311981695350551902318

./com.apple.keyboards/images/1479594642413384923311981695350551902322

./com.apple.keyboards/images/1479594642413384923314783740877995356158

./com.apple.keyboards/images/1479594642413384923314783740879069097983

./com.apple.keyboards/images/1479594642413384923315643815811881603413

./com.apple.keyboards/images/1479594642413384923317527210149397040322

./com.apple.keyboards/images/1479594642413384923317931341942450338877

./com.apple.keyboards/images/1479594642413384923317931341944597822526

./com.apple.keyboards/images/147959464241338492334233758872557782808

./com.apple.keyboards/images/147959464241338492334233758872557803293

./com.apple.keyboards/images/14795946424133849233468843410059184672

./com.apple.keyboards/images/147959464241338492334921148393448642876

./com.apple.keyboards/images/147959464241338492334921148395596126525

./com.apple.keyboards/images/147959464241338492335336395495931255650

./com.apple.keyboards/images/147959464241338492335336395497004997476

./com.apple.keyboards/images/147959464241338492337479678977386259146

./com.apple.keyboards/images/147959464241338492339632071978067975219

./com.apple.keyboards/images/147959464241338492339632071978135084084

./com.apple.keyboards/version

./com.apple.springboard.sharedimagecache/Persistent/MPUMediaControlsTitlesView.initWithMediaControlsStyle.explicitImage.medium.white.cpbitmap

./com.apple.springboard.sharedimagecache/Persistent/SBLockScreenTimerDial.SBLockScreenTimerDial.ffffffff.cpbitmap

./com.apple.springboard.sharedimagecache/Persistent/SPUIMicrophoneButton-microphone-UIDeviceWhiteColorSpace 1 0.5.cpbitmap

./com.apple.springboard.sharedimagecache/Persistent/SPUISearchField-UISearchFieldIcon.png-UIDeviceWhiteColorSpace 1 0.5.cpbitmap

./com.apple.springboard.sharedimagecache/Persistent/SPUISearchField-UITextFieldClearButton.png-UIDeviceWhiteColorSpace 1 0.05.cpbitmap

./com.apple.springboard.sharedimagecache/Persistent/SPUISearchField-UITextFieldClearButton.png-UIDeviceWhiteColorSpace 1 0.5.cpbitmap

./com.apple.springboard.sharedimagecache/Persistent/highlight-0.05a-0.5h.cpbitmap

./com.apple.UIStatusBar/13G34

./com.apple.UIStatusBar/13G34/images

./com.apple.UIStatusBar/13G34/images/1039020096324377700710198612147844925979

./com.apple.UIStatusBar/13G34/images/1039020096324377700710634339200688242802

./com.apple.UIStatusBar/13G34/images/1039020096324377700710757715578305784819

./com.apple.UIStatusBar/13G34/images/1039020096324377700711220188916602690988

./com.apple.UIStatusBar/13G34/images/1039020096324377700712425791478299626742

./com.apple.UIStatusBar/13G34/images/1039020096324377700712704003551140391248

./com.apple.UIStatusBar/13G34/images/103902009632437770071313694840112509155

./com.apple.UIStatusBar/13G34/images/1039020096324377700713442876262005646858

./com.apple.UIStatusBar/13G34/images/103902009632437770071395972756864560608

./com.apple.UIStatusBar/13G34/images/1039020096324377700714907601724399844083

./com.apple.UIStatusBar/13G34/images/1039020096324377700715954837124783310251

./com.apple.UIStatusBar/13G34/images/1039020096324377700715994728947166078266

./com.apple.UIStatusBar/13G34/images/1039020096324377700716238094646439292807

./com.apple.UIStatusBar/13G34/images/1039020096324377700716940508635111689789

./com.apple.UIStatusBar/13G34/images/1039020096324377700717042138908636756196

./com.apple.UIStatusBar/13G34/images/1039020096324377700717218532650492130641

./com.apple.UIStatusBar/13G34/images/1039020096324377700717462655569540249332

./com.apple.UIStatusBar/13G34/images/1039020096324377700718059834902139698836

./com.apple.UIStatusBar/13G34/images/1039020096324377700718369866628271492632

./com.apple.UIStatusBar/13G34/images/103902009632437770071867603135155582958

./com.apple.UIStatusBar/13G34/images/10390200963243777007327178207583790357

./com.apple.UIStatusBar/13G34/images/10390200963243777007376502352924270726

./com.apple.UIStatusBar/13G34/images/10390200963243777007395936346648846802

./com.apple.UIStatusBar/13G34/images/103902009632437770074052775587071320306

./com.apple.UIStatusBar/13G34/images/103902009632437770076865854842937718261

./com.apple.UIStatusBar/13G34/images/103902009632437770077800846775486057811

./com.apple.UIStatusBar/13G34/images/103902009632437770078189474451788651855

./com.apple.UIStatusBar/13G34/images/103902009632437770078795788739273980439

./com.apple.UIStatusBar/13G34/images/103902009632437770079497200443559453209

./com.apple.UIStatusBar/13G34/images/137231541608522814699510980251454547138

./com.apple.UIStatusBar/13G34/images/137231541608522815141002541591986238030

./com.apple.UIStatusBar/13G34/images/137790580121135907358508314467820706297

./com.apple.UIStatusBar/13G34/images/137790580121137382009366330306401698181

./com.apple.UIStatusBar/13G34/images/152884643589655972831599650543139564800

./com.apple.UIStatusBar/13G34/images/1556557664008654871012115311662581810517

./com.apple.UIStatusBar/13G34/images/1556557664008654871012836648864816460880

./com.apple.UIStatusBar/13G34/images/1556557664008654871014462076484308030628

./com.apple.UIStatusBar/13G34/images/1556557664008654871015641280022875577290

./com.apple.UIStatusBar/13G34/images/1556557664008654871015741172760947285391

./com.apple.UIStatusBar/13G34/images/1556557664008654871015922802209703464337

./com.apple.UIStatusBar/13G34/images/1556557664008654871017526780625131167876

./com.apple.UIStatusBar/13G34/images/155655766400865487103099088022943061626

./com.apple.UIStatusBar/13G34/images/155655766400865487107531719731308593096

./com.apple.UIStatusBar/13G34/images/155655766400865487108030833148378333932

./com.apple.UIStatusBar/13G34/images/155655766400865487108068631341974607195

./com.apple.UIStatusBar/13G34/images/155655766400865487109633407300224170329

./com.apple.UIStatusBar/13G34/images/172013073450246116838745071841325323094

./com.apple.UIStatusBar/13G34/images/1720130734502461399618426798578130999522

./com.apple.UIStatusBar/13G34/images/1800580936946948848514483719157810176066

./com.apple.UIStatusBar/13G34/images/49323063244341257432078866322602948395

./com.apple.UIStatusBar/13G34/images/77350990063853702457181074390759127393

./com.apple.UIStatusBar/13G34/images/773509900638537255811193522073991178477

./com.apple.UIStatusBar/13G34/images/894125213033485972717349882604744449187

./com.apple.UIStatusBar/13G34/images/913491956634634691712976029331019236010

./com.apple.UIStatusBar/13G34/images/913491956634634691713601713983705707560

./com.apple.UIStatusBar/13G34/images/913491956634634691714654605107696537094

./com.apple.UIStatusBar/13G34/images/913491956634634691714785353602473096361

./com.apple.UIStatusBar/13G34/images/913491956634634691715561209785542574055

./com.apple.UIStatusBar/13G34/images/913491956634634691716370047815794217113

./com.apple.UIStatusBar/13G34/images/913491956634634691717827247372062556614

./com.apple.UIStatusBar/13G34/images/91349195663463469172501027566307062077

./com.apple.UIStatusBar/13G34/images/91349195663463469177238126024527451290

./com.apple.UIStatusBar/13G34/images/91349195663463469177596626995019811720

./com.apple.UIStatusBar/13G34/images/91349195663463469179510860190675676465

./Snapshots/com.apple.MobileSMS

./Snapshots/com.apple.MobileSMS/com.apple.MobileSMS

./Snapshots/com.apple.MobileSMS/com.apple.MobileSMS/6B63100D-FDD5-453F-8589-A8503C7576BA@2x.png

./Snapshots/com.apple.MobileSMS/com.apple.MobileSMS/FABB44FB-F7CD-4C11-9921-C825B4E78903@2x.png

./Snapshots/com.apple.MobileSMS/com.apple.MobileSMS/downscaled

./Snapshots/com.apple.MobileSMS/com.apple.MobileSMS/downscaled/20CF91AE-6005-47F8-B20D-BF4F7454884C@2x.png

./Snapshots/com.apple.mobileslideshow

./Snapshots/com.apple.mobileslideshow/com.apple.mobileslideshow

./Snapshots/com.apple.mobileslideshow/com.apple.mobileslideshow/C9D041B1-697F-4D9E-BE4C-37E7E3477F42@2x.png

./Snapshots/com.apple.mobileslideshow/com.apple.mobileslideshow/E7D47826-A3B5-4BC9-97F7-ACF73A2D0380@2x.png

./Snapshots/com.apple.mobileslideshow/com.apple.mobileslideshow/downscaled

./Snapshots/com.apple.mobileslideshow/com.apple.mobileslideshow/downscaled/11E65FD6-19EC-489D-94AB-3CE3478947BC@2x.png

./Snapshots/com.tigisoftware.Filza

./Snapshots/com.tigisoftware.Filza/com.tigisoftware.Filza

./Snapshots/com.tigisoftware.Filza/com.tigisoftware.Filza/46DFE833-D961-44F3-9CAE-DFE13E83172E@2x.png

./Snapshots/com.tigisoftware.Filza/com.tigisoftware.Filza/57248186-D080-42D0-8A0A-0A52CE2949A9@2x.png

./Snapshots/com.tigisoftware.Filza/com.tigisoftware.Filza/downscaled

./Snapshots/com.tigisoftware.Filza/com.tigisoftware.Filza/downscaled/DA50FBDE-909A-427C-9673-76D9FCEBB8CD@2x.png

./Snapshots/net.limneos.answeringmachineapp

./Snapshots/net.limneos.answeringmachineapp/net.limneos.answeringmachineapp

./Snapshots/net.limneos.answeringmachineapp/net.limneos.answeringmachineapp/CF95664F-3DD0-40DE-B840-DFA794719E59@2x.png

./Snapshots/net.limneos.answeringmachineapp/net.limneos.answeringmachineapp/downscaled

./Snapshots/net.limneos.answeringmachineapp/net.limneos.answeringmachineapp/downscaled/9313A227-70D8-4B99-96A6-B67C16C04B24@2x.png

##
In dir: /var/mobile/Library
##

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/.store.db

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexArrays

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexCompactDirectory

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexDirectory

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexGroups

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexHead

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexIds

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexPostings

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexTermIds

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.indexUpdates

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.shadowIndexGroups

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/0.shadowIndexHead

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-1.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-1.map.data

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-1.map.header

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-1.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-2.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-2.map.data

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-2.map.header

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-2.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-3.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-3.map.data

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-3.map.header

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-3.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-4.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-4.map.data

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-4.map.header

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-4.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-5.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-5.map.data

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-5.map.header

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/dbStr-5.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/indexState

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/journalAttr.1

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/journalAttr.7

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexArrays

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexCompactDirectory

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexDirectory

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexGroups

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexHead

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexIds

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexPostings

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexTermIds

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.indexUpdates

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.shadowIndexArrays

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.shadowIndexCompactDirectory

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.shadowIndexDirectory

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.shadowIndexGroups

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.shadowIndexHead

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/live.0.shadowIndexTermIds

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/store.db

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/store.updates

./Spotlight/CoreSpotlight/NSFileProtectionComplete/index.spotlightV2/tmp.spotlight.state

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/.store.db

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexArrays

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexCompactDirectory

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexDirectory

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexGroups

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexHead

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexIds

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexPostings

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexTermIds

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.indexUpdates

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.shadowIndexGroups

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/0.shadowIndexHead

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-1.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-1.map.data

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-1.map.header

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-1.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-2.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-2.map.data

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-2.map.header

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-2.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-3.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-3.map.data

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-3.map.header

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-3.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-4.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-4.map.data

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-4.map.header

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-4.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-5.map.buckets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-5.map.data

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-5.map.header

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/dbStr-5.map.offsets

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/indexState

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/journalAttr.1

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/journalAttr.17

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexArrays

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexCompactDirectory

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexDirectory

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexGroups

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexHead

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexIds

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexPostings

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexTermIds

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.indexUpdates

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.shadowIndexArrays

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.shadowIndexCompactDirectory

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.shadowIndexDirectory

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.shadowIndexGroups

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.shadowIndexHead

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/live.0.shadowIndexTermIds

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/store.db

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/store.updates

./Spotlight/CoreSpotlight/NSFileProtectionCompleteUntilFirstUserAuthentication/index.spotlightV2/tmp.spotlight.state

##
In dir: /var/mobile
##

##
In dir: /var/root/Library/Caches
##

./com.apple.coresymbolicationd

./com.apple.coresymbolicationd/13G34

com.apple.UIStatusBar/13G34

com.apple.UIStatusBar/13G34/images

##
In dir: /var/root
##

./Library/Caches/com.apple.coresymbolicationd

./Library/Caches/com.apple.coresymbolicationd/13G34

**Comment by coolstar** [comment]
Try deleting /var/mobile/Library/Caches/com.apple.keyboards instead of running iCleaner and see if the keyboard font changes correctly with that.

**Comment by mwoolweaver** [comment]
i deleted that directory (/var/mobile/Library/Caches/com.apple.keyboards) and everything was correct after a respring

also worth noting is that directory only gets recreated when you use the keyboard

**Comment by coolstar** [comment]
ok. Anemone will be updated on the next nightly to clear that directory on a respring.

**Comment by coolstar** [comment]
This was fixed in 1.1-390
