### ISSUE TITLE
Detect if tweaks are tampering with legacy detection

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#142]
Detect if tweaks (such as HideMeX) are tampering with Anemone's legacy theme detection and block it.

**Comment by coolstar** [comment]
Initial code in 1.1-391 to address this.

**Comment by WhyIsItReal** [comment]
Why should this be blocked? It's not a feature to prevent user modification (IMO).

**Comment by Johnnyb021** [comment]
Is byta font 3 preventing user modification? I'm having a problem with downloading anemone unless I remove byta font 3

**Comment by Johnnyb021** [comment]
Or byta font tweak mode

**Comment by NewD2** [comment]
Yes. BytaFont Tweak Mode conflicts with Anemone. So it must be removed now. But Anemone can do all Font Replacement now. No need for BytaFont anymore.

**Comment by coolstar** [comment]
BytaFont was causing stability issues with Anemone, hence why Anemone conflicts with it.

**Comment by Johnnyb021** [comment]
How does anemone work in able to do change system font? What do I do

**Comment by mwoolweaver** [comment]
see the wiki page about [Fonts](https://github.com/AnemoneTeam/Anemone/wiki/Fonts)

**Comment by coolstar** [comment]
Closing. Better if we don't bother. If users install a tweak like HideMeX and aren't aware of the legacy issue, their problem.
