### ISSUE TITLE
Anemone not theming or using the wrong icon size

### ISSUE THREAD

**Issue by JaySven** [AnemoneTeam/Anemone#143]
Anemone v 1.1-393 does not change the icons on my theme at all.

The previous versions (1.1-38x) where having a problem with Anemone using the wrong icon size on homescreen for some apps (using the 80px 40x40@2x file instead of the 120px 60x60@2x).

(My theme uses different icon design for homescreen, spotlight, settings and NC).

I'm currently "forced" to use the version 1.1-345, as it is fully working (for me).

**Comment by coolstar** [comment]
Does your theme work if you revert to 1.1-392?

This is because Bundles/ is deprecated in Anemone for home screen icons. The Bundles functionality will be re-enabled in 1.1-394, but the fact that your theme broke in 1.1-393 means you'll need to convert your icons to IconBundles soon.

**Comment by JaySven** [comment]
Sort of works in 1.1-392. Some apps are using the wrong icon for home screen.
I tried adding IconBundles for home screen and leaving the spotlight, settings and nc icon in bundles, but it seems like IconBundles takes priority and overrides those.
