### ISSUE TITLE
iPad Pro and anemone fonts

### ISSUE THREAD

**Issue by ravenleighii** [AnemoneTeam/Anemone#146]
I've tried a few different fonts, doesn't seem to matter, they all seem to mess up the keyboard, portrait and landscape.

**Comment by ravenleighii** [comment]
Is there a way to ignore the iPad keyboard when applying fonts (For now) so I can use then? As it stands, with the keyboard bugging out, I can't use any of the nifty fonts being offered. Or, I can just be patient until you find time for this issue...

**Comment by coolstar** [comment]
This is an issue with the fonts not supporting iPad Pro.

**Comment by ravenleighii** [comment]
How can I help to fix this for the Ipad Pro users? Probably not many of us out here, but still. Would be nice to be able to play with the fonts too.

**Comment by mwoolweaver** [comment]
If it's an issue with every font you've tried (both my repo and dbk1ng's) then I would say try to get in contact with dbk1ng and see what he says

**Comment by ravenleighii** [comment]
I've only tried 3, I'll try a few more and get a hold of dbk1ng

**Comment by ravenleighii** [comment]
3 of the 4 fonts dbk1ng offers in (IOS 9 Anemone Fonts) work perfectly (no issues with the keyboard)  ( didn't try the 4th one as I assumed it would work too if the first 3 did.
