### ISSUE TITLE
AnemoneEffects broken since the 397 update 

### ISSUE THREAD

**Issue by iM4CH3T3** [AnemoneTeam/Anemone#147]
Only some of the icons are themed with effects how they should be. 95% are broken ...
https://www.dropbox.com/s/wgi4qhhufqdmokt/Foto%2028.08.16%2C%2018%2046%2031.png?dl=0
In this image you can see only the Reddit app themed properly..

**Comment by coolstar** [comment]
what exactly am I looking at in that screenshot?

**Comment by coolstar** [comment]
looks like #151. Will track the issue there.
