### ISSUE TITLE
Theming open folder background

### ISSUE THREAD

**Issue by dreamnet** [AnemoneTeam/Anemone#15]
Currently, it is only possible to change the shape of the (ugly) blurred open folder background by adding `FolderMask@2x~iphone.png` to `com.apple.springboard`.
I would be nice if the ability to theme the open folder background would be added to Anemone (ANEMFolderMask@2x.png?).

**Comment by coolstar** [comment]
We are looking at this now. Can you please send us a sample image that we can test with? The background should be the same size as FolderMask but should be a background, not a mask.

**Comment by dreamnet** [comment]
Here is one (@2x):
![glasklarticonfinal](https://cloud.githubusercontent.com/assets/2068130/11326557/f3b3d7c8-916c-11e5-97db-954d8763a83c.png)

**Comment by coolstar** [comment]
This is being added. Expect it in the next nightly build.

To theme the folder background, place an image named "ANEMFolderBackground" in the com.apple.springboard bundle.

**Comment by coolstar** [comment]
Added in nightly 348

**Comment by dreamnet** [comment]
@coolstar Seems to work fine, thanks!
![img_0445](https://cloud.githubusercontent.com/assets/2068130/17278251/d9a98db6-5758-11e6-9b32-31c799c72e6e.PNG)

**Comment by coolstar** [comment]
Awesome :smiley:
