### ISSUE TITLE
FolderGridImageAlpha ain't taken in consideration in theme preview

### ISSUE THREAD

**Issue by Alfroggy** [AnemoneTeam/Anemone#150]
Even with FolderGridImageAlpha set to 0.0, the theme preview screen shows the icon previews on top of folders.

Thanks for looking into this.

**Comment by Alfroggy** [comment]
Oh I do have FolderLegacyMask set to true in my enabled theme.

**Comment by coolstar** [comment]
Fixed in 1.1-405.
