### ISSUE TITLE
Several of my Anemone Effects have stopped working since 1-4xx

### ISSUE THREAD

**Issue by NewD2** [AnemoneTeam/Anemone#151]
Several of my AE have stopped working since Anenone 1-4xx. And the ones that are working / the icon moves outside the mask of the AE. See Anemone icon in screenshot below as an example.

**Comment by Alfroggy** [comment]
Load the desktop version of the site. The option is at the bottom of the comment section.

![image](https://cloud.githubusercontent.com/assets/13683006/18049254/63ac0b0c-6de7-11e6-8d3a-58aa00b461ae.png)

Then you'll have the 'selecting them' option.

![image](https://cloud.githubusercontent.com/assets/13683006/18049255/63d42326-6de7-11e6-8131-5a6e53683a13.png)

Choose from photo library. Tadaa !

**Comment by NewD2** [comment]
![image](https://cloud.githubusercontent.com/assets/21249926/18049464/74a9b322-6db6-11e6-9eff-85f9ebd4af85.png)

**Comment by coolstar** [comment]
IconEffects should be 120x120 for @2x and 180x180 for @3x. Make sure your images are the right size.

**Comment by coolstar** [comment]
Fixed in 1.1-404.
