### ISSUE TITLE
Anemone 2.0.1 took away my dock

### ISSUE THREAD

**Issue by jooseemanuel** [AnemoneTeam/Anemone#153]
I'm using the theme Blackie DDP and it had a classic dock, I had it enabled and when I updated anemone to 2.0.1 it won't display it anymore .. It shows the original iOS dock instead even tho I have my theme classic dock selected

**Comment by coolstar** [comment]
Your theme is missing an Info.plist to specify the DockMode: https://github.com/AnemoneTeam/Anemone/wiki/Dock#dockmode

**Comment by jooseemanuel** [comment]
I've checked and it does have the info.plist .. Everything was fine until the new anemone update, what can I do to get it back?
