### ISSUE TITLE
Anemone 2.0.1 removed BytaFont Tweak Mode

### ISSUE THREAD

**Issue by baddgyal** [AnemoneTeam/Anemone#154]
I just recently upgraded Anemone and I had some issues with this new upgrade. In order for me to upgrade to Anemone 2.0.1, BytaFont Tweak Mode was needed to be removed. 
Hopefully this issue will be resolved.

**Comment by baddgyal** [comment]
This is on IPhone 6s running IOS 9.3.3

**Comment by coolstar** [comment]
Anemone conflicts with BytaFont due to a known issue with BytaFont: #109
