### ISSUE TITLE
Anemone themes have a yellow "!" 

### ISSUE THREAD

**Issue by ARoso93** [AnemoneTeam/Anemone#155]
I updated Anemone from the changes in Cydia, and notice that my at the bottom on the dock the theme was looking weird, so I go check anemone and now all my themes have this yellow exclamation point. What does this mean I want my themes back 😩

**Comment by coolstar** [comment]
Dock is a separate issue (missing Info.plist in the themes). The Exclamation point means that your themes' packages are broken and need to be fixed in an update soon. However, the themes themselves should still be working.
