### ISSUE TITLE
Ability to theme settings sliders

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#157]
This post made me think of this feature: https://www.reddit.com/r/jailbreak/comments/50pp70/request_this_daynight_toggle_switch/

EDIT: While the ability to animate the change would be cool, just having 2 images (one for on, one for off) and blurring between them when you toggle it would be enough for me.

**Comment by enaloha** [comment]
Even just colorizing would be nice and could replace Tintch.

**Comment by coolstar** [comment]
This can already be done with Anemone's tint color functionality for UISwitch and UISwitchThumb: https://github.com/AnemoneTeam/Anemone/wiki/Tint-Colors#tint-color-settings

**Comment by gmawji** [comment]
You guys should probably check this out:
http://www.junesiphone.com/articles/uncategorized/anemone-color-settings/

**Comment by gmawji** [comment]
also this:
http://junesiphone.com/anemone/

**Comment by cj81499** [comment]
This doesn't really do what I want. I want to make an image be there like the post I linked to had. @coolstar

**Comment by gmawji** [comment]
Image based just cant happen anymore. There isn't an image for the background any longer, it's tint color. You would need a separate tweak that does it.

**Comment by mwoolweaver** [comment]
How does the on/off labels toggle work??

http://i.imgur.com/G1avaWq.jpg - with them on

http://i.imgur.com/UERv4JR.jpg - with them off
