### ISSUE TITLE
Pandora and TuneIn Radio Pro loading slowly

### ISSUE THREAD

**Issue by garyw1963** [AnemoneTeam/Anemone#160]
I LOVE Anenome! 

After installing Anenome, I have been having issues with both Pandora and TuneIn Radio getting stuck on the loading screen. If I uninstall Anenime the issue goes away. 

Any advice?

**Comment by coolstar** [comment]
![image](https://cloud.githubusercontent.com/assets/1431548/18420371/013ee022-7826-11e6-8c20-fa95aa2814ed.png)
Pandora is working fine here; iPhone 6, 9.3.3 with Anemone 2.0-1.

**Comment by garyw1963** [comment]
Ok, thank you for the quick response
