### ISSUE TITLE
Anemone crashed our app

### ISSUE THREAD

**Issue by lilyball** [AnemoneTeam/Anemone#164]
Fabric showed a couple of crash logs from jailbroken users that were attributed to z_AnemoneIconEffects.dylib. AFAICT that means this project, right? Here's the relevant bits from our crash, in case that's helpful to you:

```
Crashed: com.apple.main-thread
0  z_AnemoneIconEffects.dylib     0x120009088 (Missing)
1  z_AnemoneIconEffects.dylib     0x12000befc (Missing)
2  z_AnemoneIconEffects.dylib     0x12000bff8 (Missing)
3  libdyld.dylib                  0x181708ba0 dyld_stub_binder + 60
4  libswiftDispatch.dylib         0x101b17e78 specialized DispatchQueue.init(label : String, qos : DispatchQoS, attributes : DispatchQueue.Attributes, autoreleaseFrequency : DispatchQueue.AutoreleaseFrequency, target : DispatchQueue?) -> DispatchQueue (__hidden#480_:162)
… [the rest of the trace is our app]
```

The crashes occurred on 10.0.1 (14A403) and 10.0.2 (14A456), though there were only 3 reported crashes total so I don't know if this is meaningful. I also don't have an Apple-generated crash log, only the Fabric report, which means I'm missing the binary images section, but based on the addresses there you can probably figure out the slide offset for symbolication. And I have no idea what version of Anemone was installed on these devices, nor any other information for you. I'm really only reporting this crash to you out of courtesy (I don't ever jailbreak).

**Comment by coolstar** [comment]
Which app is this? Are the crashes on iOS 9 or iOS 8? We have some test devices that we can install the app on and see if we can get this issue.

Also do you happen to know when the crashes happened? that would help us at get a guesstimate of which version of Anemone was installed.

**Comment by lilyball** [comment]
The app is Postmates, and as I already said, it occurred on iOS 10. I can't tell you anything else, because I don't know anything else, beyond the fact that it occurred very early in the app's lifecycle.

**Comment by coolstar** [comment]
@kballard iOS 10 is not publicly jailbroken. Either the device in question has a private jailbreak or someone has a modified version of the app with the Anemone dylibs injected into it. Either way, the configuration is unsupported (we only support devices running a public jailbroken version of iOS).
