### ISSUE TITLE
Anemone not showing proper folder mask in iPad Preview 

### ISSUE THREAD

**Issue by SowderDev** [AnemoneTeam/Anemone#167]
Running the latest public build (2.0-1) on an iPad Air 2 on 9.3.2 
![image](https://cloud.githubusercontent.com/assets/1566732/19991668/c0c04916-a20d-11e6-97a0-b5b6ffe9bd9b.png)

**Comment by coolstar** [comment]
Just checked on my iPad Air 2 here and looks like the issue is indeed there. I'll take a look.

**Comment by SowderDev** [comment]
Thank you

**Comment by coolstar** [comment]
This was fixed a few updates ago.

**Comment by SowderDev** [comment]
I know. You posted it on slack a couple months ago. Not sure why I'm
getting a second response to this topic
