### ISSUE TITLE
ModernDock

### ISSUE THREAD

**Issue by grkka** [AnemoneTeam/Anemone#17]
Why in version 1.0.0.1 and earlier betas had the option of "ModernDock" and since leaving in Cydia no longer?

**Comment by coolstar** [comment]
ClassicDock and ModernDock have been moved to the separate "ClassicDock" package in Cydia.

**Comment by grkka** [comment]
Then I'll stay in version 1.0.0.1
;)
Thanks.

**Comment by cj81499** [comment]
@grkka Why not just install the separate package?
