### ISSUE TITLE
Please help me. i keep getting a wierd error

### ISSUE THREAD

**Issue by TomBerentsen** [AnemoneTeam/Anemone#178]
How do i fix the error that says: There was an error contacting SpringBoard please reinstall Anenome and/or RocketBootstrap.

I did reinstall bove and even deleted them and downloaded them again but they still dont work when i download the theme Foxy but it did work earlier today.

**Comment by TomBerentsen** [comment]
By the way I am on ios 10.2 jailbreak on iphone 6

**Comment by gmawji** [comment]
Are you using the beta RocketBS?

**Comment by coolstar** [comment]
Your RocketBootstrap version is too old and doesn't support iOS 10. You need to update RocketBootstrap for it to work

**Comment by TomBerentsen** [comment]
Where do i update it could je please help me

**Comment by TomBerentsen** [comment]
I have version 1.0.4

**Comment by cj81499** [comment]
@TomBerentsen did you figure it out? It's from http://rpetri.ch/reposetup/
