### ISSUE TITLE
I cant update RocketBootstrap

### ISSUE THREAD

**Issue by TomBerentsen** [AnemoneTeam/Anemone#179]
I apreasate your quick replie on my other issue.
This time i cant update RocketBootstrap it doesnt say there is a new version and i have deleted it and downloaded it several times and i reinstalled it to but is anenome still doesnt work i am rocking version 1.0.4 on RocketBootstrap. Can you please help me by telling me what to do.

**Comment by mwoolweaver** [comment]
https://rpetri.ch/repo will help you.

**Comment by coolstar** [comment]
Not an Anemone issue.
