### ISSUE TITLE
Respring logos

### ISSUE THREAD

**Issue by Shugabuga** [AnemoneTeam/Anemone#18]
Custom respring logos will not take affect with Anemone. Is this an issue with the theme itself or with Anemone?

**Comment by coolstar** [comment]
The theme needs some minor adjustments for the custom respring logo to work. Which theme are you trying to use?

**Comment by coolstar** [comment]
You can see an example respring logo theme that works with Anemone here: https://github.com/glasklart/hd/tree/master/Library/Themes/Glasklart%20Icons.theme/Bundles/com.apple.ProgressUI

**Comment by Shugabuga** [comment]
Thanks! I was using a custom respring logo, so I will update it!
