### ISSUE TITLE
Icons not theming with the last version.

### ISSUE THREAD

**Issue by BenCoro** [AnemoneTeam/Anemone#180]
My icons were not theming with the version (the one with no respring needed). iPhone SE 9.3.3. The theme is Ace El Cap and I believe it hasn't been updated for Anemone in the last few months (yellow warning sign)

**Comment by coolstar** [comment]
When you open the theme's folders in Filza, do you see an "IconBundles" folder?

**Comment by BenCoro** [comment]
There is a "Bundles" folder

**Comment by coolstar** [comment]
Your theme is out of date and needs to be updated to support IconBundles. Support for older Bundles home screen icons has been dropped.

**Comment by BenCoro** [comment]
Thanks I'll notify the creator of the theme
