### ISSUE TITLE
I can't use the app here is why

### ISSUE THREAD

**Issue by Pierre2603** [AnemoneTeam/Anemone#181]
Please help me fix this problem
![img_0952](https://cloud.githubusercontent.com/assets/25446716/22449856/ad0bf5c4-e730-11e6-83b0-be468920f30a.PNG)
![img_0953](https://cloud.githubusercontent.com/assets/25446716/22449857/ad0ca5be-e730-11e6-8e23-72dbe903539a.PNG)

**Comment by coolstar** [comment]
Wrong RocketBootstrap version installed for iOS 10.

**Comment by undead2cold** [comment]
https://youtu.be/_XGgHKSC_TY
