### ISSUE TITLE
Error When Opening App

### ISSUE THREAD

**Issue by ItZzGu5** [AnemoneTeam/Anemone#187]
When I open Anemone it will always say 'There was an Error contacting the Optitheme Daemon. Please reinstall Anemone and/or RocketBootStrap.'
I have reinstalled not Anemone and RocketBootStrap but the error is still appearing. Would you be able to help? 
Thanks.

**Comment by gmawji** [comment]
Install the beta RocketBS from **rpetrich beta repo**

**Comment by gmawji** [comment]
Btw literally the issue before yours is exactly the same. Please check next time to see if your issue has been brought up and answered.

**Comment by gmawji** [comment]
#186
