### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by grkka** [AnemoneTeam/Anemone#188]
![asset](https://cloud.githubusercontent.com/assets/14794477/22547259/2a6d4a92-e941-11e6-869e-b8b4b5e6ea08.PNG)
Hello @coolstar I have a 6S Plus iPhone IOS 10.2 with the latest version of Anemone. As you'll see on the keyboard, the fonts is modified, but in the rest of the system or apps not working. Is it my fault? Thank you.

**Comment by cj81499** [comment]
Fonts work differently in iOS 10. I believe this is normal.

**Comment by mwoolweaver** [comment]
please see below 

https://twitter.com/coolstarorg/status/826703949642084352

https://ghostbin.com/paste/stgoo
