### ISSUE TITLE
Anemone Badge Bug

### ISSUE THREAD

**Issue by LonJonn** [AnemoneTeam/Anemone#189]
After swiping through my home screen pages, badges for icons mess up a bit. this is extremely noticeable with blurry badges as you can see the red around the badges. This is what it looks like without blurry badges though.
![anemonebadgebug](https://cloud.githubusercontent.com/assets/13981703/22551884/cd7efe60-e9aa-11e6-84c3-d3cecafca426.jpg)

**Comment by cj81499** [comment]
Looks like instead of stretching like normal, the entire image is being stretched. I haven't seen this myself, but I also never have more than 20 notifications on a single app, because I check my email pretty frequently.

**Comment by coolstar** [comment]
Fixed in Anemone 2.1.1-27
