### ISSUE TITLE
Signals and telephony ui glitch

### ISSUE THREAD

**Issue by violerine** [AnemoneTeam/Anemone#190]
![img_2635](https://cloud.githubusercontent.com/assets/25447039/22552518/d79730da-e98b-11e6-8e3f-366c500efc07.PNG)
![img_2636](https://cloud.githubusercontent.com/assets/25447039/22552519/d7ef2d4e-e98b-11e6-8b6e-0d77da86ed76.PNG)
 Previous version seems more stable even tho with no signals and telephonyui

**Comment by coolstar** [comment]
On iOS 10, TelephonyUI does not load the images at all for the buttons other than "#" and "*". It draws the glyphs out by rendering the text from the font. Anemone is working as it should, and is overriding the car asset properly.

Although the images are still present in the car Assets file, they are not being used any more.
