### ISSUE TITLE
Use different emoji for themes that Anemone has completely dropped support for

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#194]
It may be a good idea to detect themes that don't have any IconBundles icons, and have app icons in the Bundles/ or Folders/ icon to have a different emoji to warn about their status, as these themes no longer function with Anemone.

Any one of these should work: ❌  ⛔️   🚫

**Comment by coolstar** [comment]
This has been implemented.

![image](https://cloud.githubusercontent.com/assets/1431548/22708905/daa131aa-ed2c-11e6-917c-1bb50fc14c57.png)

**Comment by cj81499** [comment]
*cough* This can probably be closed *cough*

**Comment by coolstar** [comment]
yeah haha
