### ISSUE TITLE
Battery icon glitched on lockscreen

### ISSUE THREAD

**Issue by Aerozolic** [AnemoneTeam/Anemone#198]
Theme is Veexillum 2.5 with Anemone 2.1.1-14. I've already tried "recache --no-respring && sleep 1 && recache"
The command used to fix this but not anymore.
http://i.imgur.com/wjTM2ag.jpg

**Comment by wilzhenesc** [comment]
I also have this issue, but the cause from my end is compatibility issue with NoBlur.

**Comment by Aerozolic** [comment]
I don't have NoBlur.
