### ISSUE TITLE
IconBundles

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#2]
When using a glyph theme that uses iconbundles, icon quality is lost and icons become harder to see. It's hard to see what I'm talking about without zooming in, but when you make icons, like me, it's easy to know when your icon doesn't look as it should.

![image](https://cloud.githubusercontent.com/assets/9152032/9111426/10060660-3c15-11e5-8aa0-2b1caa4d3e37.jpg)

The only workaround for this that I could find is setting IB-MaskIcons to true, but then the icons are on a black background and look bad.

![image](https://cloud.githubusercontent.com/assets/9152032/9111423/0427692e-3c15-11e5-9e59-3b1ce778e20c.jpg)

It see it most noticeably with the settings icon, but I can tell it's happening to all the icons.

**Comment by dreamnet** [comment]
I also described this problem [here](https://github.com/glasklart/hd/issues/5091#issuecomment-127758134). Icons themed with the IconBundles method are displayed too big. themelib also has this bug.

**Comment by cj81499** [comment]
Thanks for sharing @dreamnet. Seems like the same issue explored further. I hope @coolstar fixes this because IconBundles is so much easier to use than the traditional bundles method.

The worst part for me is that there is no way around this because IconBundles and Winterboard has the same issue. I wonder why it doesn't happen when the mask is applied. Also, any idea how Kvasir II gets around this? I just tried it and it seems to be working perfectly.

**Comment by dreamnet** [comment]
@cj81499 I am sure @coolstar will take a look at this. I am maintaining the Glasklart theme, and we have over 7800 icons themed with IconBundles. It is - nearly - impossible, to theme so much icons with the Bundles method. And yes, IconBundles itself had the same bugs - I am just wondering that nobody seems to recognize them. I reported the problem with the icon sizes also [here](https://github.com/nickfrey/IconBundles/issues/12) some time ago, but got no response from @nickfrey.

I can't check if Kvasir II has these problems or not, because I don't have it... And I can't find any good screenshots of this theme with the clock, calendar and a closed folder.

**Comment by cj81499** [comment]
@dreamnet How strange. With such a glaring issue, I'd think something would have been done by now.

I just rechecked Kvasir II and it turns out it does have the problem. I just didn't notice it before. My bad.

**Comment by coolstar** [comment]
@dreamnet @cj81499 I've been thinking of ways to fix this without breaking existing IconBundles themes.

How does this idea sound? I'll keep the existing IconBundles code and add a new "AnemoneIcons" functionality which won't have these issues. Themes can switch from IconBundles to AnemoneIcons by simply renaming the directory. That way existing themes won't be affected and themes that need the bug fixed can have it.

**Comment by cj81499** [comment]
@coolstar @dreamnet That would work, but I don't understand why you can't just change the implementation of IconBundles to work in the same way AnemoneIcons would.

**Comment by coolstar** [comment]
@cj81499 I'll try changing the existing IconBundles implementation but if it breaks any existing themes, AnemoneIcons it is.

**Comment by coolstar** [comment]
@cj81499 while I would like to fix the bug, I don't want to break any existing themes :)

**Comment by cj81499** [comment]
@coolstar @dreamnet I figured I should add onto that by saying that having iconbundles work as it does seems like a bug, and I see no way changing it would negatively impact a theme.

**Comment by coolstar** [comment]
@cj81499 I guess I'll have to see if there's any negative effects on existing themes from the fixes and decide based on that. If there isn't any, then the fix will be implemented on the existing "IconBundles" folder in Anemone.

@dreamnet I've downloaded Glasklart onto my iPhone 6 and will take a look at these issues shortly

**Comment by dreamnet** [comment]
@coolstar Sounds great, thank you!

**Comment by coolstar** [comment]
@dreamnet looking at the issue with the clock icon, it looks like there's a bug in iOS where it overlays the live image on top of the non-live image (Apple never noticed as they don't use translucency). I'll fix this in the next Anemone nightly anyways.

**Comment by dreamnet** [comment]
@coolstar Soundls like christmas to me. :dancers: :smile:

**Comment by coolstar** [comment]
I have removed the mask images from Glasklart and fixed the black clock icon issue in Anemone and this is how it looks so far.

![img_0008](https://cloud.githubusercontent.com/assets/1431548/9279312/835e8d9c-426b-11e5-8f05-816533ac694a.PNG)

**Comment by coolstar** [comment]
@dreamnet drew a few grid lines on top for reference. How does this look?

![image](https://cloud.githubusercontent.com/assets/1431548/9279426/55137168-426c-11e5-855b-92de74c69995.png)

**Comment by dreamnet** [comment]
@coolstar Need a view minutes to check that...

**Comment by nickfrey** [comment]
We should not have a separate tweak just to fix these issues.

IconBundles itself really shouldn't exist standalone, but the creator of WinterBoard wasn't interested in merging it into WB. @coolstar, I'm happy you came up with a solution, but it would be far better to come up with a general solution as many themes use IconBundles and are affected. At the very least, submitting a pull request to IB would be appreciated so we can keep these efforts organized. I can spend some time this weekend looking into a general solution as well.

**Comment by coolstar** [comment]
@nickfrey the fix I applied doesn't appear to break any themes so I have kept the folder as IconBundles and haven't created an AnemoneIcons folder

**Comment by cj81499** [comment]
All of this sounds awesome! I'm so glad to see the small list of problems getting smaller by the day (and in this case, hour). Thanks for the great fixes @coolstar! When can we expect to see these in Cydia?

**Comment by coolstar** [comment]
@cj81499 I'm currently waiting on approval from @dreamnet regarding the fix and will push nightly 268 :)

**Comment by dreamnet** [comment]
@coolstar Only the Newsstand icon in the screenshot above is displayed correctly (120x120px), all other icons are displayed too big (124x124px). All other icons than the newsstand (and the Clock) icon are themed with the the IconBundles-method in Glasklart.

**Comment by coolstar** [comment]
@dreamnet ah, I see. Let me try something.

**Comment by cj81499** [comment]
One other thing, any chance the page in Cydia could have a depiction with a changelog? Even just a link to a google doc changelog or something? I'd be glad to code one for you if you would add it to the repo.

**Comment by coolstar** [comment]
@cj81499 I plan on adding a depiction page once Anemone is no longer a nightly. For now you can check @Anemone_iOS on twitter for updates.

**Comment by coolstar** [comment]
@dreamnet aside from the obvious clock sizing issue, it appears that I've been able to fix the sizing :)

All icons (aside from clock) are 120x120

![image](https://cloud.githubusercontent.com/assets/1431548/9280887/3c55b73a-4276-11e5-9cae-2ccf71ab28e7.png)

**Comment by coolstar** [comment]
Testing with another IconBundles theme (Amury) it looks like this fix doesn't break other IconBundles themes

![image](https://cloud.githubusercontent.com/assets/1431548/9280967/b4cd574a-4276-11e5-8079-7f26742e7bd1.png)

**Comment by dreamnet** [comment]
@coolstar Woooohooow!!! Looks fine to me and now the icons are as sharp as they should be. Next round's on me! :beers: I try it out on my iPad if you are adding this fix to the next nightly.

**Comment by coolstar** [comment]
Fixed the clock icon sizing issue so looks like we're good :) 

![image](https://cloud.githubusercontent.com/assets/1431548/9281100/af839866-4277-11e5-86b4-dd5372892059.png)

**Comment by dreamnet** [comment]
@coolstar Yes, looks like that's it! :+1: 
@cj81499 Also happy with it?

**Comment by coolstar** [comment]
Fixed in Anemone nightly 268.

**Comment by cj81499** [comment]
Looks good to me! Trying it out now.
