### ISSUE TITLE
Conflict with Flipswitch/Activator on iOS 10

### ISSUE THREAD

**Issue by stah83** [AnemoneTeam/Anemone#200]
I can apply a theme and everything works fine. But when I have to respring Springboard (because of cydia updates etc.) my iPhone crashes at the entering code/Touch ID screen and I have to reboot.
That happens with every theme.

**Comment by stah83** [comment]
I sorted out that it has something to do with Flipswitch or Activator. After uninstalling these tweaks everything works fine.

**Comment by mwoolweaver** [comment]
@coolstar this can be closed

**Comment by stah83** [comment]
Why should this be closed? I still got issues with anemone! 

I would love to use Activator AND anemone together, but can't do this.

**Comment by kr0n1k** [comment]
@stah83 are you still having the same issues? Because I had to remove Activator too 😞😞

**Comment by stah83** [comment]
@kr0n1k After updating to new Version 2.1.1-27 everything works great! I can use Activator and Anemone together now without any issues 👍
