### ISSUE TITLE
Anemone.dylib Crashed

### ISSUE THREAD

**Issue by imrobbyrc** [AnemoneTeam/Anemone#204]
im on iphone 5s running ios 10.2 , when i try applying theme anemone was crash and going to safe mode, i check in crash reporter suspect was anemone.dylib, and that issues coming because harbor or infinidock installed, when i disable them , anemone stop crashing,

**Comment by RickyX3** [comment]
On Harbor do you have the setting at the very bottom "use normal dock background" enabled? It might fix the crashing

**Comment by imrobbyrc** [comment]
Yes i was enable it, but still crashing when applyimg theme, do i need to uncheck no background dock on anemone ?

**Comment by RickyX3** [comment]
You can try that. I switched themes and now I haven't had any crashes related to Anemone.

**Comment by imrobbyrc** [comment]
i was try that, but still crashing,  try another theme, still crashing,, also i try disable harbor in setting , resping and applying theme in anemone , anemone still crashing but if i disable harbor in icleaner anemone doesnt crash anymore,

**Comment by imrobbyrc** [comment]
try downgrade anemone from 2.1.1.-16 to 2.1.1-6 and  2.1.1-8 and apply theme , its fix crashing ,work without crashing anemone.dylib,, but i try downgrade to 2.1.1-11 it crash again

**Comment by RickyX3** [comment]
i can't downgrade

**Comment by imrobbyrc** [comment]
download from apt bigboss, search on google and you will see the lastest version , in the link just change anemone_2.1.1-16 to anemone_2.1.1-8,

hope @coolstar will fixed this, because crashed happend on anemone 2.1.1-11 and up.

**Comment by RickyX3** [comment]
It's okay, I changed themes & am no longer experiencing crashes on 2.1.1-16

**Comment by imrobbyrc** [comment]
some people have crash like me in reddit , i think this issue happend to some devices only ,,

are you using anemone and bytafont ? because im using they both maybe bytafont cause this issue

**Comment by RickyX3** [comment]
I removed bytafont a while ago because it was making anemone crash. I miss the fonts but some themes come with nice fonts.

Try disabling bytafont via iCleaner and see if that helps you.

**Comment by imrobbyrc** [comment]
okee thank you bro @RickyX3

**Comment by RickyX3** [comment]
@rbych18 no problem :)

**Comment by coolstar** [comment]
Harbor conflict has been fixed in 2.1.3
