### ISSUE TITLE
Anemone Doesn't Automatically Theme some Icons.

### ISSUE THREAD

**Issue by samirbhujel** [AnemoneTeam/Anemone#206]
When You apply The theme It doesnot Automatically Theme some icons like cydia and You have to press and use the alternate Thing to theme it and its so annoying everytime You apply theme it does that.
https://twitter.com/SuperMirSa/status/834228346770845696

**Comment by RickyX3** [comment]
@samirbhujel Have you tried clicking on preview & applying the theme. You always have to re spring when changing themes.

**Comment by samirbhujel** [comment]
Dude There is a feature In new anemone ou dont have to respring but also i did i tried everything (reinstall,remove,use icleaner,and other things

**Comment by RickyX3** [comment]
@samirbhujel try downgrading

**Comment by samirbhujel** [comment]
@RickyX3 i did it works on 2.0.1

**Comment by coolstar** [comment]
Fixed in 2.1.1-27

**Comment by samirbhujel** [comment]
@coolstar Alright Thanks
