### ISSUE TITLE
Anemone causes safe mode crash and breaks apps on 7+

### ISSUE THREAD

**Issue by ColbyRoark** [AnemoneTeam/Anemone#209]
I'm aware that the 7+ is not supported by anemone at all, and have since uninstalled the tweak, but I would like to post this just in case this can be resolved sooner and hopefully lead to a more stable anemone. After installing anemone and running my own theme on it, I crashed into safe mode. No big deal, just go into Cydia and uninstall. However, if you don't uninstall on this first chance, your phone will boot into no jail broken mode, but your apps will be unusable. Settings, Cydia, and mach_portal will all crash of cause a respring. I was able to duplicate this twice, both times requiring an iCloud wipe and restore. 
Hopefully this provides some help to making anemone stable by the time a stable 10.1.1 jailbreak is released!

**Comment by coolstar** [comment]
mach_portal is not supported. If the issue still happens with extra_recipe please open a new issue for this.

**Comment by luixiuno** [comment]
What issue are we moved to? @coolstar @ColbyRoark
