### ISSUE TITLE
[Request] Icons on LockScreen

### ISSUE THREAD

**Issue by grkka** [AnemoneTeam/Anemone#210]
Hi @coolstar I would like to make a request, is there any way to make the icons do not change on the lock screen? In my case I use the theme "Glasklart" and being all with the same color, no distinguishing notifications. Thank you.
![asset](https://cloud.githubusercontent.com/assets/14794477/23543632/519ab366-fff3-11e6-94cd-43d3d46ab95b.PNG)

**Comment by coolstar** [comment]
Not possible to implement. Icons are loaded by SpringBoard from the same function irrespective of whether it's on the lock screen or home screen.
