### ISSUE TITLE
Icons in TODAY view widgets not theming.

### ISSUE THREAD

**Issue by throughtheiris25** [AnemoneTeam/Anemone#211]
Two things really. Using the latest Anemone on Yalu 10.2. 

1) Icons on the TODAY view widgets in the notification center do not use their respective home screen themed icons.
2) Clock icon in SIRI APP SUGGESTIONS do not use their respective control panel clock icon.

Anyhow, I'm sure something has changed or the icons are defined elsewhere. I have tried 5 iOS 10 supported themes, and none of them resolves the issue. Obviously, all the standard steps have been tried, including checking the Wiki, reapply jailbreak, and disabling tweaks which may be conflicting. 

If this is not an issue, please don't me to the write IconBundle to add the respective icons to or maybe a WIKI page I missed.  

Thanks in advance.

**Comment by cj81499** [comment]
Try running recache in terminal. I believe this is due to not respringing after applying a theme.

**Comment by throughtheiris25** [comment]
Thanks for the response. As I mentioned, reapplied jailbreak, which means I completely restarted the device, which means that happened automatically. I did a UI cache clearance in terminal, re-cache and some other things too during my testing. 

Maybe they are just not themed by all of these themes, that's why I'm trying to determine if there is some IconBundle that the Today views use for icons. Nothing in the Wiki, so maybe one of you special folks know.

Anyhow, does Today View Widgets get themed on your end? Do you have any notification tweaks enabled if this is the case?

**Comment by gmawji** [comment]
Today views need a new hook. Not sure when or if this is even going to be implemented. They may not even be files we can theme.

**Comment by throughtheiris25** [comment]
Thought as much. I just decided to hide it everywhere until that day comes. Don't really need it, do we! Thanks for the response.

**Comment by gmawji** [comment]
I kinda like it lol. I deal with looking at those rubbish stock icons.

**Comment by throughtheiris25** [comment]
Those stock icons are the end of humanity man. Star Wars' Death Star was created to destroy those icons, but it seems they never got that far because they always end up getting destroyed!
