### ISSUE TITLE
iOS 9.2-9.3.4 32-bit jailbreak issues

### ISSUE THREAD

**Issue by 14dcutaneo** [AnemoneTeam/Anemone#214]
I have an iPad 4 on iOS 9.3.3, and an iPhone 5 on iOS 9.3.3. Whenever I restart my phone or iPad and re-apply the jailbreak, I always get an error from anemone saying "There was an error contacting the optitheme daemon. Please reinstall anemone and / or rocketbootstrap. " This is only on my 32 bit devices, as my iPhone 6s Plus on iOS 10.2 does not have this issue. I've also noticed similar problems with other apps that do not function properly unless reinstalled after rebooting with this jailbreak, such as F.lux. Any advice would be great :)

**Comment by coolstar** [comment]
Works fine on 32 bit iOS 9.0.2, 64 bit iOS 9.3.3 and 64 bit iOS 10.2. Likely a problem with the jailbreak, not with Anemone.
