### ISSUE TITLE
Embedded Safari not playing videos

### ISSUE THREAD

**Issue by diggitydogg** [AnemoneTeam/Anemone#219]
I have disabled all tweaks using iCleaner Pro. Once I enable Anemoneicons.dylib the embedded Safari view will no longer play any videos. Browsing over to www.reddit.com/r/videos in an embedded view consistently will not play anything. Doesn't matter if it's a YouTube video or liveleak or even animated gifs. If I jump out to full Safari it is fine. Using an iPhone 6s 10.2 Anemlne 2.1.1-27

**Comment by coolstar** [comment]
Fixed in #222
