### ISSUE TITLE
Safari View Controller won't play videos with AnemoneIcons.dylib on

### ISSUE THREAD

**Issue by Aransh** [AnemoneTeam/Anemone#222]
iPhone 7 Plus, iOS 10.1.1, YaluX+Extra_Recipe Beta 4 (also experienced this issue with Mach_Portal Beta 3).
Videos will simply load forever in Safari View Controller, opening the video on normal Safari fixes it but it REALLY bothers me as I use Safari View Controller to watch videos daily. Debugging with iCleaner showed the AnemoneIcons.dylib causes it

**Comment by coolstar** [comment]
Anemone 2.1.2 will be going live shortly with some updates to that dylib in question. Once that is out let me know if the problem still exists there.

**Comment by Aransh** [comment]
@coolstar I've just updated to 2.1.2 and I'm still having this issue, video just loads infinitely, opening it up in full safari loads the video in 2 seconds

**Comment by coolstar** [comment]
Fixed in 2.1.3-3. Give this deb a try and it should be fixed: https://www.dropbox.com/s/fta45qxiazx3fqy/com.anemonetheming.anemone_2.1.3-3_iphoneos-arm.deb?dl=0

**Comment by Aransh** [comment]
Works! Thanks a lot 🙏🏽

**Comment by coolstar** [comment]
2.1.3 is on BigBoss now
