### ISSUE TITLE
ShareSheet with Anemone 2.1.2-2

### ISSUE THREAD

**Issue by grkka** [AnemoneTeam/Anemone#223]
ShareSheet does not work well with the latest Anemone update. iPhone 6s+ iOS 10.2 Theme Glasklart or Veexillum

![asset](https://cloud.githubusercontent.com/assets/14794477/26640676/b4bfd694-4628-11e7-9bc7-d8be671e5a4a.PNG)

**Comment by coolstar** [comment]
Fixed in 2.1.2-3

**Comment by grkka** [comment]
👍🏻
