### ISSUE TITLE
Help settings app crashes when i go in storage settings

### ISSUE THREAD

**Issue by GmDashJesus15** [AnemoneTeam/Anemone#227]
When i jump in to settings then i go en general then storage & icloud usage and when i click on manage storage i crashes :(

**Comment by GmDashJesus15** [comment]
Help pls fix this bug

**Comment by jm26200** [comment]
For me same crash
If remove anemone no crash
Reinstall by Cydia only the lag possible, crash again
Also remove last version and install version 2.1.3-2.deb and no crash !
Wait correction now
iPhone 7 iOS 10.1.1 j. YaluX 1.1.1

**Comment by ASDFGHJKL101** [comment]
@jm26200 Could you link the .deb file? Thanks

**Comment by gmawji** [comment]
Do NOT link any debs here at all.

**Comment by ASDFGHJKL101** [comment]
@jm26200 Then could you send it on reddit or something? To https://www.reddit.com/user/ASDFGHJKL_101/

**Comment by ASDFGHJKL101** [comment]
Made a post about this earlier:

https://www.reddit.com/r/jailbreak/comments/6f6oux/help_seems_like_the_latest_update_of_anemone/

**Comment by jm26200** [comment]
Yes it's ok with link u post copy link in safari and u can install with iFile
And after same me wait correction...

**Comment by tehuno** [comment]
@its crashing when the app icons aren't cached or loaded inside the settings app and you try to view them too fast...

For instance if you scroll to bottom of the settings app too quickly before the little icons load it can crash...
 So if you slow scroll down or just wait a second and let them load, than it will work fine.  Its odd.  So its only a real issue if you close settings app from switcher or respring.  But very annoying.

**Comment by jm26200** [comment]
For me it's ok iPhone 7 jb yaluX 1.1.1
com.anemonetheming.anemone_1.3-2_iphoneos-arm.deb
https://www.reddit.com//user/coolstarorg
Gooood  now  :)

**Comment by jm26200** [comment]
https://www.reddit.com//user/coolstarorg

Sorry for error hope good now

**Comment by jm26200** [comment]
hi all
With upgrade 2.1.3-4 same crash  !!!!

**Comment by tehuno** [comment]
if you arent on stable JB then anemone won't be stable.  did you see tweet?  he posted old version there......

new version is great on 10.1.1 stable jailbreak

**Comment by jm26200** [comment]
My  JB  very  stable  no more tweaks  never  crash before ...

and  back   with this  version same   give   with link up

![img_0419](https://user-images.githubusercontent.com/29171027/26969522-515cb6d2-4d06-11e7-8199-391b56592034.PNG)

**Comment by tehuno** [comment]
What iOS and jailbreak did you use and what iphone?  That is what i mean by stable... only extra recipe is stable on iOS 10.  See tweets for old deb and what I am talking about... check twitter and reddit for for info.

 Here is answer for you:

https://twitter.com/Anemone_iOS/status/872532087907131392

https://twitter.com/Anemone_iOS/status/872524134139412480

https://twitter.com/Anemone_iOS/status/872524295691354113

https://twitter.com/Anemone_iOS/status/872518918128115712

https://twitter.com/Anemone_iOS/status/871551654692179968

https://twitter.com/Anemone_iOS/status/871551539357155328

**Comment by jm26200** [comment]
hello  sir

ty  for  try  help me  with  last  version anemone !!!

i have  iPhone 7 with  ios 10.1.1  and  Jailbreak with *extra_recipe+yaluX
beta3.ipa* try  before    with  the  first *mach_portal+yalu-b3.ipa *but
same  always  crash  when go on *setting-general-Stokage&icloud-manage
storage *when  touch   back SB  and  message crash  send log  but ...with
anemone 2.1.1-27 no pb all ok
have  nice  day
regard

2017-06-09 11:38 GMT+02:00 tehuno <notifications@github.com>:

**Comment by tehuno** [comment]
> i have  iPhone 7 with  ios 10.1.1  and  Jailbreak with *extra_recipe+yaluX
> beta3.ipa*

You are using old version.  There is beta 4 of extra recipe out.   I have no issue with crash on ios 10.1.1 extra_recipe beta 4.  Do not use mach portal.  No crash here anemone 2.1.3-4 . 

Check other tweaks, bad theme, reboot rejailbreak with new version, and clearing cache should fix issue, jm26200.  Also if you have modify font it could be cause.

**Comment by jm26200** [comment]
i have  try beta4   but  very long put 1 days  and  half   for arrival
jb   and  no keep :(

maybe try one  other  day  beta4 !

ty   for  all  sir

2017-06-09 12:13 GMT+02:00 tehuno <notifications@github.com>:

**Comment by jm26200** [comment]
hello  all

Great  thanks for  last  version at all team  Anemone this  version 2.1.4-3 no  crash and  we  can  go stokage&icloud   and  Mnage  storage  
ty  at all

**Comment by coolstar** [comment]
Fixed in 2.1.4-2
