### ISSUE TITLE
Preferences crash after respring

### ISSUE THREAD

**Issue by Potterd** [AnemoneTeam/Anemone#228]
Tapping on Notifications entry in Preferences causes Preferences to crash after each respring.  This problem is fixed after another entry in Preferences is opened successfully.

Restoring Anemone to version 2.1.1-27 eliminates the problem.  This appears to have been introduced with the most recent version.

Please let me know if yo need anything additional to fix.

**Comment by coolstar** [comment]
Fixed in 2.1.4-2
