### ISSUE TITLE
Icon effects for settings icons

### ISSUE THREAD

**Issue by dreamnet** [AnemoneTeam/Anemone#23]
@coolstar Well you know I'm the maintainer of the Glasklart theme, witch has over 8100 icons so far and Glasklart is a very white/transparent theme. Thanks to Anemone the icons of Glasklart are looking very good now and we can theme a lot more than just the normal springboard icons, but we are running into a problem with the icons that are shown in the settings (they are taken from the IconBundles, that's a very good thing so we don't have to make extra icons for the installed apps), a picture says more than thousand words:
<img src="https://cloud.githubusercontent.com/assets/2068130/10291124/4516287c-6ba8-11e5-8164-2718031de2a5.PNG" width="150">
As you can see, we have white/transparent on white here.... :cry: 
I know it is possible to theme the settings with tint colors and override colors to make the settings background dark, but that's not what we want at all, so I request the ability to add 58x58px Overlays|Underlays/Shadows for the settings icons (the same thing as you have done for the normal icons with [icon effects](https://github.com/AnemoneTeam/Anemone/wiki/Icon-Effects), but for the settings icons).
I already have a settings theme ready, but I don't want to add it to Glasklart as long we have a mixed result:
<img src="https://cloud.githubusercontent.com/assets/2068130/10291587/e792d95e-6baa-11e5-9630-7285503bfd2c.PNG" width="150">
THX for checking!

**Comment by coolstar** [comment]
Shouldn't be too difficult. I'll take a look.

**Comment by dreamnet** [comment]
@coolstar :+1:

**Comment by coolstar** [comment]
We are adding an Underlay option in Anemone 1.2. Does this sound good?

https://github.com/AnemoneTeam/Anemone/wiki/Icon-Effects

**Comment by coolstar** [comment]
This has been added to 1.1-30 on the fast ring repo. Please try it out and let me know how it works out.

**Comment by dreamnet** [comment]
@coolstar Oh yeah, sounds good! - Give me a view minutes to try it out.

**Comment by gmawji** [comment]
So same as the AnemoneEffects Icon Shadow but for everything else? Yes PLEASE!
Going to test now.

**Comment by coolstar** [comment]
@jokerg7 Underlays work similar to Overlays but are applied underneath the icon. Unlike shadows, they have the limitation that they can't extend past the icon.

**Comment by gmawji** [comment]
@coolstar meaning the iconmask is the limitation for these correct? It will cut off anything past that option?

**Comment by coolstar** [comment]
@jokerg7 well actually it's the icon size that is the limitation, not the mask itself

**Comment by dreamnet** [comment]
@coolstar Seems to work fine for the settings icons - I need to test a bit more and if I find any errors or unexpected behavior I check back here.
https://cloud.githubusercontent.com/assets/2068130/10716860/0694a30e-7b47-11e5-95e6-f9daece8f69a.PNG

**Comment by coolstar** [comment]
Underlay functionality is added and working properly.

**Comment by dreamnet** [comment]
[Here](https://github.com/glasklart/hd/issues/6594) is a list of all settings icons and there paths I know so far.
P.S.: @coolstar Thank's for the cardump, this helped a lot!
