### ISSUE TITLE
iCloud Drive settings crashing due to AnemoneUIKit.dylib

### ISSUE THREAD

**Issue by Aransh** [AnemoneTeam/Anemone#232]
iOS 10.1.1 (Extra_Recipe), iPhone 7 Plus (Hebrew-RTL)
I am unable to open the iCloud-iCloud Drive settings, crash reporter claims AnemoneUIKit.dylib is the culprit, AnemoneIcons.dylib also appears as a suspect

**Comment by coolstar** [comment]
Fixed in 2.1.4-2
