### ISSUE TITLE
Storage settings crashing due to AnemoneIcons.dylib and AnemoneUIKit.dylib

### ISSUE THREAD

**Issue by Aransh** [AnemoneTeam/Anemone#234]
iOS 10.1.1 (Extra_Recipe), iPhone 7 Plus (Hebrew-RTL)
I am unable to open the General-Storage & iCloud usage-Manage storage settings, crash reporter claims AnemoneUIKit.dylib and AnemoneIcons.dylib are the culprits. The settings page opens, loads the apps and then crashes.

**Comment by coolstar** [comment]
Fixed in 2.1.4-2
