### ISSUE TITLE
iPad mini 4, battery icon is weird

### ISSUE THREAD

**Issue by ghost** [AnemoneTeam/Anemone#239]
Even though I have 20% battery remaining, the icon of my battery on my status bar looks as if it's about to die. It happens even when I have no themes enabled. Works fine when I remove anemone

**Comment by svet6ma** [comment]
Same

**Comment by svet6ma** [comment]
iPhone 6,  iOS 10.2

**Comment by svet6ma** [comment]
Same, iPhone 6, iOS 10.2
