### ISSUE TITLE
Dock Reflection disables Icon Labels Shadow

### ISSUE THREAD

**Issue by 1davi** [AnemoneTeam/Anemone#24]
After configuring the icon labels shadow in the plist file I enabled the "Dock Reflection" option in Anemone, but doing so disabled the icon labels shadow.

**Comment by coolstar** [comment]
that's... strange. The Dock and Icon Labels stuff are in separate dylibs (AnemoneDock.dylib and AnemoneIcons.dylib). I'll take a look.

**Comment by coolstar** [comment]
Is this issue still present in the latest version?

**Comment by 1davi** [comment]
No, the problem is gone, thanks!
