### ISSUE TITLE
Slider Fix

### ISSUE THREAD

**Issue by ghost** [AnemoneTeam/Anemone#25]
The slider on Lockscreen is not themeable

**Comment by coolstar** [comment]
which part of the lock screen slider are you trying to theme? On iOS 7+ it's mostly really just text on top of the user's wallpaper unless 3rd party tweaks are applied.

**Comment by ghost** [comment]
the arrow of the slide to unlock.

**Comment by coolstar** [comment]
Does this issue still happen on the latest 1.1-56?

**Comment by IamFenixDesign** [comment]
yes.

**Comment by coolstar** [comment]
What path were you using to theme the arrow?

**Comment by IamFenixDesign** [comment]
path?

**Comment by cj81499** [comment]
File location and name

**Comment by IamFenixDesign** [comment]
file location. Bundles: com.apple.UIKit and name: UIGlintyStringViewChevron.

**Comment by cj81499** [comment]
Just for future, writing that as "/Bundles/com.apple.UIKit/UIGlintyStringViewChevron.png" is a pretty universal way to show where something is and its name.

**Comment by coolstar** [comment]
Try /UIImages/UIGlintyStringViewChevron.png

**Comment by IamFenixDesign** [comment]
Yeah it work thanks

Enviado desde mi iPod

El 24 nov 2015, a las 03:57, CoolStar <notifications@github.com<mailto:notifications@github.com>> escribi?:

Try /UIImages/UIGlintyStringViewChevron.png

##
