### ISSUE TITLE
Shadow with Gridswitcher

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#26]
When using AnemoneEffects to apply a icon shadow (and maybe overlay too, I only used a shadow), the icon shadow does not change based on Gridswitcher settings. Even if the icon is disabled, the shadow still appears.

![image](https://cloud.githubusercontent.com/assets/9152032/10327843/4db54a80-6c7a-11e5-9b08-450c3ac3a3b3.jpg)

**Comment by 1davi** [comment]
I remember this same problem happening with Iconomatic, maybe it's a GridSwitcher bug.

**Comment by cj81499** [comment]
Could be. I'm hoping that @coolstar can maybe look at Gridswitcher's settings to resolve this

**Comment by cleverjackal** [comment]
This issue wasn't solved, was it?

**Comment by cj81499** [comment]
The issue is still present. I can't have icon shadows because of it.

**Comment by cleverjackal** [comment]
Oh :/ I suppose CoolStar won't work on it anymore

**Comment by cj81499** [comment]
I hope he does. I would like to have shadows, but can't deal with this issue in Gridswitcher.
