### ISSUE TITLE
anemone is dead

### ISSUE THREAD

**Issue by jm26200** [AnemoneTeam/Anemone#271]
Hello everyone
After jeailbreak ios 11.1.2 with Electra 1.0.2
Installing anemone tweak with cydia everything is ok
respring
icon on the screen but opens and closes immediately ...
Regards

**Comment by grkka** [comment]
@jm26200 http://rpetri.ch/repo/ Add this repo to Cydia in install the latest version of RocketBootStrap

**Comment by jm26200** [comment]
hello
i  make   before   and   install  last    beta   and  reinstall  anemone
but  see  error  no good  install
look  pic
ty  sir


2018-03-02 8:57 GMT+01:00 grkka <notifications@github.com>:
