### ISSUE TITLE
sorry  make error and close  but no want close  :(

### ISSUE THREAD

**Issue by jm26200** [AnemoneTeam/Anemone#272]
Hello everyone
 After jeailbreak ios 11.1.2 with Electra 1.0.2
 Installing anemone tweak with cydia everything is ok
 respring
 icon on the screen but opens and closes immediately ...
 Regards
[](url)

**Comment by grkka** [comment]
@jm26200 As I mentioned in another post, you have to add the repo of http://rpetri.ch/repo/ and install the latest version of RocketBootStrap. Restart the iPhone, redo JB by deactivating "Tweaks" and then delete Anemone. Respring and with the latest version of RocketBootStrap installed, reinstall Anemone

**Comment by jm26200** [comment]
ty  sir  i  try   afternoon  for  me
have  nice  day
i  said  if  all ok after  this  manip
regards

2018-03-02 11:14 GMT+01:00 grkka <notifications@github.com>:

**Comment by jm26200** [comment]
just   finish  and  always  same pb

he can not find two files
1- /usr/lib/libsubstrate.dylib
2- /usr/lib/librocketbootstrap.dylib
and   also  one  other
/var/lib/dpkg/info/com.anmonetheming.anemone.postinst
line 12: 5205 Abort trap recache --no-respring
after this  line
Installed Anemone (iphoneos-arm)
and  ask  for  respring  ...
ty  for   try  help me  but  think   wait  other  version  if  coolstar
put  other and if no   return   on beta 11.3
ty  sir

2018-03-02 11:59 GMT+01:00 JM 26200 <jm26200@gmail.com>:

**Comment by jm26200** [comment]
all ok  now  after  use delectra-master and reset  all  iPhone install  last version electra  and  after 2/3 see install cydia
for  anemone  put  repo  rpetri.ch/repo/ install  rocketbootstap (beta but last ..)  respring
after  install anemone  
respring all ok
put theme  and  now  wait no make  more  ;)
tireddd
great thanks sir grkka and  other  dont remember name  
best  regards  at all ..
