### ISSUE TITLE
Updated to Anemone 2.1.7-2 some weird issue

### ISSUE THREAD

**Issue by unix43** [AnemoneTeam/Anemone#281]
Hi.

I upgraded to anemone 2.1.7-2 today from -1 and some of my icons changed to a blokes face.
It ranged from safari to photos to calendar some Cydia apps.
I turned off my theme didn’t change anything.
I turned anemone off it was doing it with stock icons.
So I downgraded anemone everything was fine again.
Upgraded same thing.
Deleted anemone ran iCleaner reinstalled no change. So downgraded and just leaving it atm.

![9cf795d9-3b7d-4dff-91a0-8085a9504203](https://user-images.githubusercontent.com/23280814/38170092-b6bc1932-35ae-11e8-9ed2-74c25856e9aa.png)
![5ffae838-bfbb-4180-b9cc-2c1a7451cf0a](https://user-images.githubusercontent.com/23280814/38170093-b704ed1a-35ae-11e8-8686-817cf2b885c1.png)

This is what it initially looked like. Safari has a face and it was taking over my Cydia apps icons.
All tweaks themes are legit no piracy at all. AppCake I have but do not use.

Thanks.

**Comment by RYU81** [comment]
lol me too but I downgrade and everything got fix

**Comment by bgrau2020** [comment]
Same here, needs to get fixed 😏

**Comment by grkka** [comment]
It’a joke Spring Fools
