### ISSUE TITLE
Updated Anemone

### ISSUE THREAD

**Issue by Mirac2011** [AnemoneTeam/Anemone#282]
How to return to my normal icons. I uninstalled anemone downgraded anemone. But ist still appears.

**Comment by terrorzwerg** [comment]
Clear The anemonecache  var/stash or run icleaner

**Comment by Mirac2011** [comment]
I did but files are coming back with filza. Which line do i have to remove with icleaner in preferences.

**Comment by terrorzwerg** [comment]
If you deinstall Anemone so you can remove all Anemone plist in The Preference in icleaner

**Comment by Mirac2011** [comment]
I did it all. Even downgraded anemone. But icons are still upside down. Kinda weird. This far beyond than an april first prank. Not funny. :(

**Comment by Mirac2011** [comment]
Downgrading Eclipse X to 5.0.7.1 solved the problem with the upside down icons. 🙂
