### ISSUE TITLE
Anemone Icons Not Applying To Wallet Apps

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#288]
https://www.reddit.com/r/jailbreak/comments/8cqtzc/help_anemone_icons_not_applying_to_wallet_apps/

**Comment by asoksevil** [comment]
Some more screenshots:

https://m.imgur.com/r7oS91T

https://m.imgur.com/uNWVWes

**Comment by asoksevil** [comment]
I found out something new today. I removed the HSBC app today and the Apple way icon just became like this:

https://i.imgur.com/TI44UbW.jpg 

I really don't know what's happening. The glyph icon "works" (making it the original theme) if the app is present, if not it's just that blank icon.
