### ISSUE TITLE
Example missing

### ISSUE THREAD

**Issue by TheDevStudent** [AnemoneTeam/Anemone#29]
At the bottom of the page it says, "An example ... available below. It uses Custom Blurs..." but there is no example for Custom Blurs.

**Comment by cj81499** [comment]
Um...

![image](https://cloud.githubusercontent.com/assets/9152032/10430572/ec0ed208-70cd-11e5-9997-f0245e2294e7.jpg)

**Comment by TheDevStudent** [comment]
I saw the example plist, but it doesnt use custom blurs

**Comment by cj81499** [comment]
Oh. I see. I didn't look very closely.

**Comment by TheDevStudent** [comment]
I did figure it out though

![](https://pbs.twimg.com/media/CRIECiHWsAAdTKc.jpg)

**Comment by cj81499** [comment]
Do you mind sharing your .plist? I'd like to see how.

**Comment by TheDevStudent** [comment]
here 

![](http://i.imgur.com/fp5k2Hj.jpg)

**Comment by cj81499** [comment]
Great! Thanks.

**Comment by coolstar** [comment]
Wiki has been updated by TheDevStudent.
