### ISSUE TITLE
Clock icon loses theming in closed folder

### ISSUE THREAD

**Issue by dreamnet** [AnemoneTeam/Anemone#3]
When the clock icon is moved into a closed folder, it is not themed in the closed folder view anymore.
Clock icon
![](https://cloud.githubusercontent.com/assets/2068130/9122210/acd590f6-3c87-11e5-9e2f-27f8d1c789c2.png)
moved to a closed folder
![](https://cloud.githubusercontent.com/assets/2068130/9122214/b5d97082-3c87-11e5-906c-84aa5c1d99b3.png)
results in this:
![](https://cloud.githubusercontent.com/assets/2068130/9122219/bfea1cf2-3c87-11e5-9215-a01771851d45.png)

**Comment by coolstar** [comment]
how are you theming the clock icon? there's 2 different clock icons, one in SpringBoard, which is used when the clock icon is "live" and one in the clock app itself, which is when it is not live. When it is in a closed folder, the clock switches from "live" to "non-live" mode.

**Comment by dreamnet** [comment]
@coolstar Ah, found out the clock icon can be themed by adding `Bundles/com.apple.mobiletimer/icon-about@2x.png` (80x80px) on iPad. So this is not a bug - Sorry! Thanks again for your help. Closing.

**Comment by cj81499** [comment]
What should I be using for iPhone?

**Comment by dreamnet** [comment]
@cj81499 On iPhone I dont have this problem, just theme the Clock icon with the IconBundles-method.
