### ISSUE TITLE
Custom folders are jumbled

### ISSUE THREAD

**Issue by enaloha** [AnemoneTeam/Anemone#30]
I have quite a few custom folders. They are properly named and show up fine on my 6plus. For unknown reasons and without a clear pattern or trigger, they become all jumbled up in that the custom icons for Music or Video or Photo adopt folder images of other custom folders (e.g. Travel, Social, Productivity). A respring will fix this, but the mix up will happen again.

**Comment by enaloha** [comment]
Okay, looks like a few issues have been flagged as bugs, but the folder mixup is not labeled yet. So here is what happens: 

I can respring the phone and all folders show up fine. I can then let the phone sleep and leave the phone untouched for a while. Upon unlocking I see this:

![jumbled](https://cloud.githubusercontent.com/assets/13284542/10597303/29c8ff18-7689-11e5-8cf4-4c7bc279b48d.jpg)

Normal app icons remain fine, but the folders have all the wrong icons. A simple respring and they return to the proper state:

![respring](https://cloud.githubusercontent.com/assets/13284542/10597320/60a797f6-7689-11e5-9111-79943a07a63c.jpg)

But then after some variable time (minutes or tens of minutes) the mixup returns. This is with Anemone 1.1-22 on iOS 9.0.2 on iPhone 6plus.

**Comment by coolstar** [comment]
Fixed in Anemone 1.1-67

**Comment by enaloha** [comment]
Now working fine again. Thank you.
