### ISSUE TITLE
Custom Ringtone Function Broken

### ISSUE THREAD

**Issue by haroldt1234** [AnemoneTeam/Anemone#31]
Custom ringtone function is severely crippled. ToneEnabler was forcibly removed on update. 

Custom ringtones can be applied as the default ringtone. Previously, using ToneEnabler, custom ringtones could also be applied on a per contact basis - Contacts -> Contact Name -> Edit -> Ringtone. Now, if your custom is set as default it appears in the list (obviously as it being the default means it is the one applied, but other customs do not appear in the list only stock or purchased tones.)

If you would like to take over the ToneEnabler function and force it to be removed, fine, but if you are going to forcibly remove it on upgrade/install then the functionality needs to be the same or better, not less

**Comment by coolstar** [comment]
We'll remove ToneEnabler functionality from Anemone and allow installing the standalone ToneEnabler tweak in the next version.

**Comment by coolstar** [comment]
ToneEnabler functionality has been removed from Anemone's codebase and the conflict has been removed to allow standalone ToneEnabler. This will be in the next build on the fast ring repo.

**Comment by haroldt1234** [comment]
Thank you

**Comment by haroldt1234** [comment]
Last comment, rereading my original comment now and I was a dick. Thank you for addressing
