### ISSUE TITLE
Label shadows not working.

### ISSUE THREAD

**Issue by kaebiene** [AnemoneTeam/Anemone#34]
I saw on the wiki that for anemone, the code had changed for label shadows (https://github.com/AnemoneTeam/Anemone/wiki/Icon-Labels#example-plist) so I tried it out in a plist yet there's no change at all. Cydia tweaks such as Classic Labels for iOS 7.1 & 8 don't work enough unless used with Winterboard.

**Comment by coolstar** [comment]
Looks like there's a bug in the shadow renderer. To workaround it for now set a shadow color.

**Comment by coolstar** [comment]
Edit: the shadow color needs to be set. The Example has one set. Odd it isn't working for you. I'll try it and see right now.

**Comment by coolstar** [comment]
ok I've confirmed the bug here. Working on a fix.

**Comment by coolstar** [comment]
Fixed in Anemone 1.1-38 on the fast ring repo.

**Comment by kaebiene** [comment]
Thank you! Since you've updated ClassicLockScreen, my setup is complete now <3
