### ISSUE TITLE
Facebook paper can't be themed 

### ISSUE THREAD

**Issue by maaya1989** [AnemoneTeam/Anemone#35]
As the title says,the Facebook paper app can't be themed, my guess is anemone can't theme folders inside folders, as the path of paper is /Folders/Paper.app/CajmereResources/Icons/blue or /Bundles/com.facebook.Paper/CajmereResources/Icons/blue. The only solution for now is use the iconbundle method, but as winterboard can theme it the traditional bundles way, I'm sure anemone would be able to do that too, otherwise the traditional bundles theme method isn't fully supported.

**Comment by coolstar** [comment]
Can you try this dylib and let me know if it fixes the issue? (Replace AnemoneCore.dylib)

https://dl.dropboxusercontent.com/u/59964215/AnemoneCore.dylib

**Comment by coolstar** [comment]
Fixed in test dylib. Changes merged into Anemone source and will be in next nightly.
