### ISSUE TITLE
Anemone issue

### ISSUE THREAD

**Issue by Alvaro858** [AnemoneTeam/Anemone#36]
Cant work with Ayecon and Ayeris theme

**Comment by jithatsonei** [comment]
Going to have to elaborate there bud.

Why, and post logs if nessecery

**Comment by Alvaro858** [comment]
When you install ayecon or ayeris it removes anemone at the same time

**Comment by coolstar** [comment]
this is a problem with ayecon's and ayeris's packaging. For ayeris you can instead install "ayeris for Anemone" from https://coolstar.org/publicrepo/
