### ISSUE TITLE
Install keeps Cydia from opening

### ISSUE THREAD

**Issue by madroix** [AnemoneTeam/Anemone#38]
I just upgraded from a iPhone 6+ to a 6+s and when I went to download from the nightly repository there was nothing there. After investigating I see that the current version of 1.1-22 was available from the stock resources. When I installed that i could use it but I could no longer open Cydia. Furthermore I have not been able to rectify the issue unless i do a complete factory restore and rejailbreak, then restore my iPhone backup. I have narrowed the tweaks down and Anemone seems to be the issue with Cydia refusing to open. So I guess my question is two fold...
1) Is this a known issue?
2) Is there a workaround?

**Comment by coolstar** [comment]
I have tested Anemone on a friend's 6s+ and Cydia opens fine on it with 1.1-22. It seems it's another tweak you have installed.

**Comment by madroix** [comment]
It happens even if it is the only tweak I have installed after clean restore of the 9.0.2 firmware. Not sure how to get an error log but I will share it if someone can help me to retrieve it. Also is the version you are using from the regular source of the nightly. If from nightly, how are you getting it as my source for nightly doesn't have any files available.

**Comment by coolstar** [comment]
My friend downloaded the version from BigBoss (1.1-22) and it worked fine on his 6s+.

**Comment by madroix** [comment]
I am not sure what happened but the newest version doesn't crash. Something must have changed in the 1.3 release. Either way it is working great now.
