### ISSUE TITLE
FolderIcons not working?

### ISSUE THREAD

**Issue by benklinger** [AnemoneTeam/Anemone#4]
Installed Anemone and managed to use the themes that came pre-loaded. Also able to use themes downloaded from Cydia.

I want to use an image for a folder.
Went to: /Library/Themes/

And created a new folder called "Folders.theme"
Inside, added Bundles\com.apple.springboard\ANEMFolderIconBG@2x.png

The file size is 120px*120px.

Can't see it in the preview or after I respring.

Am I missing something?

iPhone 6, 8.3

**Comment by coolstar** [comment]
Have you added a 1x image as well under ANEMFolderIconBG?

**Comment by benklinger** [comment]
you mean ANEMFolderIconBG.png? Yes, I added and it still doesn't work.

**Comment by coolstar** [comment]
@benklinger what setup are you using? I know folder icons are working for other themes with Anemone. You can see https://github.com/glasklart/hd as an example of a theme that uses folder icon backgrounds.

**Comment by benklinger** [comment]
@coolstar glasklart worked. thanks. Is there a way to make the icons inside folders transparent? See the Pebble folder icon on top.
![img_3761](https://cloud.githubusercontent.com/assets/2004146/9297678/d9d1a406-44ab-11e5-8501-d615696b5648.PNG)

**Comment by coolstar** [comment]
Works with Glasklart.
