### ISSUE TITLE
Underlays inside SpringBoard

### ISSUE THREAD

**Issue by dreamnet** [AnemoneTeam/Anemone#41]
Overlays and/or shadows applied with Icon Effects are not shown in closed folders.
Example:
![](https://cloud.githubusercontent.com/assets/2068130/10750735/a2e0bdc8-7c79-11e5-90cf-6cee25c9c944.png)
The background of the left icon is applyed using Icon Effects (`AnemoneEffects/iPhoneShadow@2x.png`). This background is not shown on the "mini-icons" in the right, closed folder.

Edit: IconEffects are also not shown in Spotlight, ect.

**Comment by coolstar** [comment]
Hmm, this seems like an instance where Underlays inside SpringBoard would come in handy as shadows really shouldn't be inside folder icons.

**Comment by dreamnet** [comment]
@coolstar Hmmm, I think the icons in the closed folders should look the same as they are looking in springboard (only smaller, naturally :wink:). So I think it is necessary that Overlays and Shadows are shown in the "mini-icons" in closed folders. Also, here is a screenshot from spotlight (swipe down) on my device (iPhone 6, iOS9.02), using IconEffects (Shadow) for the icon background as shown above:
![img_0341](https://cloud.githubusercontent.com/assets/2068130/10888983/68e39b0c-818f-11e5-9430-d7f0a521739b.PNG)
An other way to solve this may be adding an extra png to use for closed folder icon backgrounds/spotlight icon backgrounds.... to Anemone.

**Comment by coolstar** [comment]
This feature will be in the next nightly build. The names are "iPhoneUnderlaySpringBoard.png" and "iPadUnderlaySpringBoard.png" (add @2x/@3x as required). They function just like underlays but are inside SpringBoard while the other underlay is inside apps.

**Comment by dreamnet** [comment]
@coolstar Sounds great, thanks! :+1:

**Comment by coolstar** [comment]
This feature is now available in 1.1-53 on the fast ring repo.
