### ISSUE TITLE
Tint Colors

### ISSUE THREAD

**Issue by gmawji** [AnemoneTeam/Anemone#42]
Hi,

Using the tint colors it doesn't seem possible to colorize the all the status bar elements, see the attached image.

![2015-10-20 02 28 03](https://cloud.githubusercontent.com/assets/7138919/10829787/7c6dceda-7e52-11e5-900d-9a36550ac37a.png)

**Comment by coolstar** [comment]
Can you upload the Info.plist you're using?

**Comment by cleverjackal** [comment]
This might also be a bug with Nightmode. Happens to me

**Comment by TheDevStudent** [comment]
I had this issue and i found a workaround 
First image is the buggy plist, just change "global" to #fffff0 and see if your issue is the same as mine and then find a color that doesn't cause it,
https://twitter.com/TheDevStudent/status/652502048777338880

**Comment by cleverjackal** [comment]
So you don't use Nightmode or libstatusbar, do you?

**Comment by ghost** [comment]
The key in override colors BlackColor does this tho the status bar. After removing the BlackColor key status bar tint as it should.

**Comment by gmawji** [comment]
Sorry it took so long mate.

Plist here: https://www.dropbox.com/s/v835nxmw44ou6wt/Info.plist?dl=0

**Comment by coolstar** [comment]
Plist issue. The status bar color needs to be slightly off-white or off-black or iOS will try to override it.

**Comment by cleverjackal** [comment]
Thanks
