### ISSUE TITLE
New update today ruined folder icon support 

### ISSUE THREAD

**Issue by beaudacious1** [AnemoneTeam/Anemone#45]
I have an iPhone 5 that worked flawlessly with anemone until this latest update, which has broken folder icon masking. I had a round icon on it that is now stock

**Comment by coolstar** [comment]
Folder Icon theming has changed in the latest update: https://github.com/AnemoneTeam/Anemone/wiki/Folder-Icons

Themers can either update to the new implementation (fast) or use FolderLegacyMask (works as before but slightly slower).

**Comment by beaudacious1** [comment]
Is this something I could do myself without much trouble? 
The theme I'm using is Aura, which has round, but not completely round icons

**Comment by coolstar** [comment]
Put this in Info.plist and drop it into a theme.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>FolderLegacyMask</key>
    <true/>
</dict>
</plist>
```
