### ISSUE TITLE
Fixing up the wiki page

### ISSUE THREAD

**Issue by n0mar** [AnemoneTeam/Anemone#47]
Hi I contacted coolstar and the dedicated twitter account for Anemone (I know I didn't send it too long ago, but ill write a post on here too to save time and you can have more characters on here etc)

Over at [Label Settings Keys](https://github.com/AnemoneTeam/Anemone/wiki/Label-Settings-Keys) there are the Keys (FontName, FontSize, etc), but there's no information as to what data type you should use (String, int, real, etc). For using TextColor with BadgeSettings, (I'm not sure if this was correct) I tried using "string", like _below_, but i got sent to safe mode.

```
...

<key>BadgeSettings</key>
  <dict>
    <key>TextColor</key>
      <string>opacity: 0</string>
  </dict>

...
```

(Edit: doing `rgba(0, 0, 0, 0)` seemed to of fixed this - which still has the same effect as opacity is a 0)

Also in saying this, custom badges are horribly broken. It's cool that you can use your own dimensions (I firstly used 120x120, thinking it would downscale down to fit the proper size etc -- I eventually got down to 4x4 (as I didn't really need to have a massive canvas just for a minimal circle badge), but it seems to of duplicated it horizontally, as a line ([here's](https://cloud.githubusercontent.com/assets/3734562/10902391/4d0de4ec-8251-11e5-9d23-7ca92d897631.png) the image)

TextXoffset and TextYoffset never work and always seem to go into the top right corner. I even added a minus ("-") to the `real` but it actually kept going up and was actually half blocked off. I changed to `integer`, but there was no difference.

Also, in the wiki, `HeightChange` & `WidthChange` are noted in an example, but theres no explanation as to what they do, nor are they on the "Label Settings Keys" page :confused:

**Comment by coolstar** [comment]
I have updated the Wiki to add more details.

**Comment by ghost** [comment]
Sadly, there is still no info about `HeightChange` & `WidthChange`, can you please describe what happens when we specify these values? Thanks
