### ISSUE TITLE
Crashes at Startup

### ISSUE THREAD

**Issue by jtown5000** [AnemoneTeam/Anemone#48]
iOS 7.1.2, iPhone 4

After most recent update, Anemone crashes at startup. Also appears to cause other apps to crash at times. (Cydia crashed when going to "installed" tab, Mail crashed when trying to load an email.)

**Comment by coolstar** [comment]
Seems like there's an issue that affects 7.x. I'll take a look later today.

**Comment by PoulPe67** [comment]
Same with iPhone 5 iOS 7.1.2 :,(

**Comment by roguedarkjedi** [comment]
Also on 7.1.2. Crashing occurs in Flex 2, Reminders, Settings, in addition to Cydia and Mail.

**Comment by coolstar** [comment]
Can any of you upload a crash report and syslog so I can figure out what's causing this issue?

**Comment by PoulPe67** [comment]
How i can, for sending u crash report ?

**Comment by cj81499** [comment]
I'm not a dev, but Pastebin links are generally good.

**Comment by coolstar** [comment]
Fixed in Anemone 1.1-51. Tested on iPhone 4 iOS 7.1.2.
