### ISSUE TITLE
Clock Background not themeable with IconBundles on iPad

### ISSUE THREAD

**Issue by dreamnet** [AnemoneTeam/Anemone#5]
@coolstar Tried to theme the clock background with the IconBundles-method on retina iPad (Anemone nightly 275, iOS 8.4) but had no luck at all.

I removed `ClockIconBackgroundSquare@2x~ipad.png` from `com.apple.springboard` and added `com.apple.mobiletimer@2x~ipad.png` to IconBundles, but Anemone seems to ignore this file. Also tried different filenames (~ipad@2x, ~ipad, @2x, ...) - nothing works.

The funny thing is, that in the preview of Anemone the Clock icon it is shown, but themed folders are not shown and the Newsstand icon has a black background:
![img_0988](https://cloud.githubusercontent.com/assets/2068130/9288583/d7f62fa8-434d-11e5-93d1-50777bc0111b.JPG)

Here is a screenshot of the theme when applied:
![img_0989](https://cloud.githubusercontent.com/assets/2068130/9288590/173b09c2-434e-11e5-8a92-77c2d912d14a.PNG)

**Comment by coolstar** [comment]
the IconBundles method themes the "non-live" mode of the clock icon (when it's in a folder, spotlight, siri, etc.). You need to use Bundles with ClockIconBackgroundSquare to theme the "live" mode of the clock icon.

**Comment by dreamnet** [comment]
@coolstar OK, thank's for clearing that out. Please update the WIKI with that information, because I think

[The clock icon background may be themed either with Anemone's car support **or** by using Anemone's IconBundles support.](https://github.com/AnemoneTeam/Anemone/wiki/Clock#background)

is a very confusing information in this case.

**Comment by coolstar** [comment]
@dreamnet ok, I have updated the wiki to clarify about both clock icon modes.

**Comment by dreamnet** [comment]
@coolstar :+1:
