### ISSUE TITLE
Third-party apps' extensions not theming correctly

### ISSUE THREAD

**Issue by maaya1989** [AnemoneTeam/Anemone#50]
I'm not sure if it's a bug or something, but icon effects can't be applied on third-party apps' extensions.
![img_0062](https://cloud.githubusercontent.com/assets/13052129/10956034/6a489c5c-8358-11e5-8765-8e94d2d95f3d.jpg)
Here's a screenshot, as you can see, icon overlay is perfectly applied on iOS' own extensions, but not on third-party apps' (metapho and import to vsco). I'm not sure if anemone can do something about it, it just feels weird to see part of them themed and others not...

**Comment by coolstar** [comment]
Issue confirmed here on iPhone 6, iOS 9.0.2 with Metapho. Investigating.

**Comment by coolstar** [comment]
Fixed. Will be included in next fast ring build.
![image](https://cloud.githubusercontent.com/assets/1431548/10980524/3898bbd8-83b7-11e5-97ad-c6b9b23c9120.png)

**Comment by coolstar** [comment]
If you don't mind me asking, where's the first picture in your screenshot from?

(I'm quite an anime junkie here)

**Comment by maaya1989** [comment]
lol I know, I was gonna say it will be a gift for you. Here's the link
http://www.pixiv.net/member_illust.php?mode=medium&illust_id=53339678

I'm not sure if this site is english ready, but you definitely should register and keep it, lots and lots pretty stuff ;)

**Comment by coolstar** [comment]
@maaya1989 cool, thanks :)

**Comment by coolstar** [comment]
This fix is now available in Anemone 1.1-51.
