### ISSUE TITLE
Folder Icons Not Rounding like they're supposed to

### ISSUE THREAD

**Issue by KGeetings** [AnemoneTeam/Anemone#52]
The folder icons show on the preview that they will be rounded, but after the restoring they are not rounded(they are the default folders). I am on an iPhone 5s iOS 9.0.2

**Comment by coolstar** [comment]
The preview feature needs an update to the new folder implementation. We'll sort this out in a future build.

**Comment by coolstar** [comment]
Preview updated in 1.1-62
