### ISSUE TITLE
Overlay for Settings Icons

### ISSUE THREAD

**Issue by gmawji** [AnemoneTeam/Anemone#54]
Hi,

Can we have the Settings icons pull a different overlay? Main reason I ask if this is possible is the current overlay is a 186x186 size on an iPhone 6 Plus. As you are aware, settings icons have a limitation of 87x87 and cannot go passed this canvas. This leaves the 186x186 overlay to be cropped to small and leaves the edges of Settings Icons sticking out.
This can be fixed in part by making the Settings icon mask small in the mobileicons.framework however it cuts off part of the icons then. Also Appstore apps pickup the overlay but stock settings apps such as airplane, cellular, etc do not so this overlay would fix that issue hopefully?

**Comment by coolstar** [comment]
Anemone should already be re-sizing the overlays automatically for the settings icons.

**Comment by gmawji** [comment]
Stock icons not picking up overlay ![](http://i.imgur.com/XFqXMZu.jpg) and highlight AppStore icon edge is protruding from overlay ![](http://i.imgur.com/SvG1MQ2.jpg)

**Comment by coolstar** [comment]
Yes, overlays only apply on top of the app store icons in Settings. This is normal. As for the icons protruding, have you checked that your mask matches up with your overlays? You can try my CircleIcons theme to verify this isn't an issue with Anemone

**Comment by gmawji** [comment]
Okay I'll try your theme to double check. I was also asking if it is possible to have the overlay show on stock settings icons. Otherwise each setting icon has to be remade for every different overlay. For example XiDr will have 7/8 overlays. So I have to make 7/8 stock settings icon sets.

**Comment by coolstar** [comment]
no it is not possible to have the overlay show on the stock settings icons. Only on the app store apps

**Comment by gmawji** [comment]
Ah damnit. Are Underlays supported on the stock ones?

**Comment by gmawji** [comment]
Figured out the mask issue. Settings icon masks have to be slightly smaller than the appicon mask to fit the overlay ![](http://i.imgur.com/G2Zc5S8.jpg)
