### ISSUE TITLE
Preview Dock Issue

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#56]
Seems to show the dock twice or something strange. Image attached.

![image](https://cloud.githubusercontent.com/assets/9152032/11225607/29284664-8d49-11e5-8d14-c3f8954e3e85.png)

**Comment by coolstar** [comment]
Can you send the Dock theme that's being used?

**Comment by cj81499** [comment]
"aweosme dock" From ModMyi. That's not a typo by the way. I'm using an iPod 5 with the iPhone Dock. (Not the 5 icon one).

**Comment by coolstar** [comment]
We have fixed this issue. The fix will be in the next nightly.

**Comment by cj81499** [comment]
Sounds good. I'll report back here to confirm after the update.

Just some other assorted preview things:

I found another issue. The status bar shows the theme that's currently applied rather than what it is has been changed to.

It would also be nice if it showed a badge on an icon so you can preview that as well.

**Comment by coolstar** [comment]
This should be fixed now in 1.1-67

**Comment by coolstar** [comment]
Status bar doesn't seem like it's fixable due to caching unfortunately :/

**Comment by cj81499** [comment]
Just tested. Dock working properly now.

It's too bad about the Status Bar. I hope you can find a way to get it to work.

What about the Badges?

Also, any chance you could have the Changelog on the page in Cydia? I'd be glad to write up the depiction for you.
