### ISSUE TITLE
Issue with NC Widget

### ISSUE THREAD

**Issue by emrehh** [AnemoneTeam/Anemone#57]
Hi, 

I want to tell you one issue I have with Anemone. 

When Anemone is installed and activated the Notification Center widgets of the apps 'News Republic' [1] and 'Appy Geek' [2] doesn't work any more. They don't update und they are not touchable (they don't open when touching on a news). 

I had the issue with 1.1-56 and hoped that it is solved with your update to -64 but it's still the same. 

I know exactly that Anemone ist causing this issue because I tried it a long with activating and inactivating every single cydia tweak. 

The links for the mentioned apps are: 
[1] „News Republic“ von News Republic
https://appsto.re/de/nOTzx.i
[2] „Appy Geek - Tech-Nachrichten“ von News Republic
https://appsto.re/de/GZwkA.i

In winterboard are no issues but I want to stay at anemone. Can you solve this problem?

Thanks. 

Greetings from germany

**Comment by coolstar** [comment]
Does this issue happen if you disable all Anemone dylibs with iCleaner except for AnemoneCore and AnemoneUIKit?

**Comment by emrehh** [comment]
Yes, it happens. After disabling AnemoneUIKit the widget worked again.

**Comment by coolstar** [comment]
Can you get a crash log for the widget from CrashReporter?

**Comment by emrehh** [comment]
There are no crash logs for these widgets. Seems they are not crashing. Only not refreshing and not touchable. 

https://www.dropbox.com/s/w6tja04i0ewryzd/Datei%2020.11.15%2C%2002%2036%2001.png?dl=0

Appy Geek still shows the news from the time I inactivated the AnemoneUIKit lib. The News Republich widget shows nothing because I added it just now. 

All other widgets I have work as usual.

**Comment by emrehh** [comment]
NC widgets working again since last Anemone update. Thanks!!

**Comment by emrehh** [comment]
Update to 1.1-85 destroyed the two NC Widgets again. 1.1-83 was better, how can I downgrade?

**Comment by coolstar** [comment]
Strange, I checked the difference between 83 and 85. Not much changed that would affect this. Does this issue still happen on the latest nightly?

**Comment by emrehh** [comment]
Everything is fine. It works since some updates ago. Thanks

**Comment by coolstar** [comment]
Alright awesome.
