### ISSUE TITLE
Feature Request: One size fit all

### ISSUE THREAD

**Issue by enaloha** [AnemoneTeam/Anemone#58]
I am wondering whether it would make sense to have a theme with icons of the largest size (180x180) and use that to theme any and all devices without the need for 2x, 3x, or ~ipad suffixes. Anemone should know the device it is running on and simply scale the icon appropriately for the device.

**Comment by coolstar** [comment]
with IconBundles, this is indeed possible. Use the -large.png suffix. Anemone will use that and size it to whatever is needed on that particular device.

**Comment by coolstar** [comment]
I would recommend using 300x300

**Comment by enaloha** [comment]
That sounds awesome, but does not seem to work for me. I made an IconBundle icon 300x300 and named it ...-large.png. It seems that Anemone accepts the suffix and shows the icon, but does not scale it down. Instead it shows up full size but clipped by the 180x180 mask on my iPhone 6 Plus.

**Comment by ArkLotif** [comment]
Use this Info.plist with your theme or add it to your current Info.plist: http://www.mediafire.com/view/dycy91x0b7zjl78/Info.plist

**Comment by enaloha** [comment]
Adding IB-Masks - true does indeed scale the icon down, but also creates a black background rounded rectangle behind my icons:

![image](https://cloud.githubusercontent.com/assets/13284542/11326546/8d4e213e-9110-11e5-8d22-1dbeda808e18.png)
