### ISSUE TITLE
Beta Repo Depictions

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#59]
This isn't so much of a bug as a request.

It would be nice if the beta repo's had a depiction.

I decided to make one that you could use. The only thing you would have to do is update the changelog with each update, which should be easy enough to figure out (I'm glad to help if you can't get it.)

[Download](http://www.mediafire.com/download/x52vg1xsfymbs87/Anemone_Depic.zip)

Screenshot: 
![anemone depic screenshot](https://cloud.githubusercontent.com/assets/9152032/11315979/a03d1a40-8fc9-11e5-9800-4434e5c8d2af.png)

**Comment by coolstar** [comment]
We have made a few minimal adjustments and published it on the fast ring repo! Thanks :)

**Comment by cj81499** [comment]
Looks good except the changelog doesn't seem to have the css stylesheet working properly.

**Comment by coolstar** [comment]
ah, right. there was a path issue. I have fixed it.

**Comment by cj81499** [comment]
Looks good now! Thanks.
