### ISSUE TITLE
Clock Icon

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#6]
The Clock icon looks fine when in a folder (bottom right folder named "Utilities"), 

![image](https://cloud.githubusercontent.com/assets/9152032/9293378/cc411804-43f6-11e5-9f4f-479e5f5d9cfd.jpg)

but when the folder is opened or the icon is moved out of the folder, the icon is made too large.

![image](https://cloud.githubusercontent.com/assets/9152032/9293379/e45511fc-43f6-11e5-9669-612a69c1d7e2.jpg)

Theme is indigo and enkel with indigo applied above enkel.

**Comment by coolstar** [comment]
Fixed in nightly 278.

**Comment by cj81499** [comment]
Thanks!
