### ISSUE TITLE
Anemone not theming localization strings

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#60]
Allow theming localization strings.

https://www.reddit.com/r/iOSthemes/comments/3tbf9n/question_simple_question_about_how_anemone/

**Comment by coolstar** [comment]
Added in 1.1-366

**Comment by cj81499** [comment]
@coolstar Can you explain how to do this?

**Comment by coolstar** [comment]
This feature was rolled back/removed in 1.1-370 because it was causing lag and problems with iMovie and some other apps

**Comment by cj81499** [comment]
Dang. Okay. Any plans to add it again?
