### ISSUE TITLE
-large does not scale down

### ISSUE THREAD

**Issue by enaloha** [AnemoneTeam/Anemone#61]
Not sure if the closed issue is read by anyone. Coolstar suggested that large icons (e.g. 300x300 named with the -large suffix would be scaled properly to any device. I made an IconBundle icon 300x300 and named it ...-large.png. It seems that Anemone accepts the suffix and shows the icon, but does not scale it down. Instead it shows up full size but clipped by the 180x180 mask on my iPhone 6 Plus.

**Comment by coolstar** [comment]
Please send us a sample icon to test with.

**Comment by enaloha** [comment]
Here is one for the Apple calculator

![com apple calculator-large](https://cloud.githubusercontent.com/assets/13284542/11326450/30ca27e8-910e-11e5-93b5-e5961a0b89f6.png)

**Comment by coolstar** [comment]
Tested and verified fix on iPhone 6 iOS 9.0.2 without IB-MaskIcons set.
![image](https://cloud.githubusercontent.com/assets/1431548/11460203/7af63c6e-969d-11e5-9265-182e4dd63b38.png)

**Comment by coolstar** [comment]
Fixed in Anemone 1.1-79.

**Comment by enaloha** [comment]
Very nice. Works perfectly. Thanks. I hope we can get this for folders as well.
