### ISSUE TITLE
Springboard page dots

### ISSUE THREAD

**Issue by subywrex** [AnemoneTeam/Anemone#62]
I would like to request the ability to theme the springboard page dots. Currently we have to use magic dots which works a little weird in its self as you have to make them up side down for them to appear right side up

**Comment by coolstar** [comment]
Please upload a 14x14 white on transparent page dot image for us to test with.

**Comment by subywrex** [comment]
Why so small? Magic dots uses a 20x20 for @1x so would be 60x60@3x

**Comment by coolstar** [comment]
@subywrex that's the size SpringBoard uses internally

**Comment by subywrex** [comment]
Most like to make them larger so maybe not have such small size perimeters if possible.  I'm not home at the moment but here is my magic dot package if that will help 

https://www.dropbox.com/s/shrb9r36d7d3y35/com.magicdots.zip?dl=0

**Comment by subywrex** [comment]
Just checking in on this. Seen it was added and removed to the 1.2 milestone.  Is it looking like something like this will be able to be done?  Would love to get rid of magic dots it just controls to much for something we install to just theme the page dots

**Comment by coolstar** [comment]
it seems like for this to be a useful enough feature to replace MagicDots it seems we'll need to implement more functionality, which will take longer.

**Comment by subywrex** [comment]
What kind of functionality.   All people want is a way to theme the page dots.  Just like we theme icon badges.  No need for custom functions.  Just an asset for themers to replace.   The people who want the customs functions of magic dots can keep magic dots.

**Comment by cj81499** [comment]
@coolstar I gotta agree with subywrex here. This doesn't need to be anything fancy. Just a small little adjustment.

**Comment by coolstar** [comment]
This is being added to the next nightly. Expect it soon :)

**Comment by coolstar** [comment]
This has been added to 1.1 nightly build 349

**Comment by coolstar** [comment]
Documentation: https://github.com/AnemoneTeam/Anemone/wiki/Page-Dots
