### ISSUE TITLE
Springboard Crash

### ISSUE THREAD

**Issue by In5pired0ne** [AnemoneTeam/Anemone#63]
Every time I install the cydia tweak anemone and touch respring. When my device comes up my springboard crashes and goes into safemode until I remove anemone.Then I checked crash reporter and it's because of cydia tweak iAppLock. I was wondering could you and the developer try to fix this? So I can use your tweak.
DEVICE: Iphone 6 ios 8.4

**Comment by coolstar** [comment]
Can you isolate the conflict to a specific dylib from Anemone? If you can do that we can take a look.

**Comment by In5pired0ne** [comment]
I don't think I can because while the tweak is installed i cant get into my device to disable. unless there's  another way than using icleaner pro.

**Comment by coolstar** [comment]
you can use Filza. Browse to /Library/MobileSubstrate/DynamicLibraries and move the dylibs out temporarily

**Comment by In5pired0ne** [comment]
ok i'm finally in  icleaner. so you want me to disable all or keep them on and turn off 1 by 1

**Comment by gmawji** [comment]
1 by 1 to determine which one is conflicting.

**Comment by In5pired0ne** [comment]
ok currently doing now

**Comment by In5pired0ne** [comment]
anemonedock.dylib is the one crashing

**Comment by coolstar** [comment]
ok. can you get the crash log and syslog from crash reporter?

**Comment by In5pired0ne** [comment]
yes, were do i send them, and should i add my id so you know who it's from?

**Comment by In5pired0ne** [comment]
ok i just sent them trough crash reporter, and there's a link down below to them.

**Comment by In5pired0ne** [comment]
also here a link to the files

https://dl.dropboxusercontent.com/u/108110405/(github)%20In5pired0ne%20anemone%20crash%20reports.zip

**Comment by coolstar** [comment]
I see a bunch of packages that you have installed from the piracy repo "insanelyi". As per policy, we will not fix any tweak conflicts that occur with pirated tweaks. Please remove the pirated tweaks and send us a crash log if it still crashes with the tweaks removed.

**Comment by cj81499** [comment]
@coolstar Cracking down on piracy like a boss

**Comment by In5pired0ne** [comment]
I have removed all the piracy tweaks that I can find and I  have purchased them (I HOPE I GOT ALL OF THEM), and my springboard is still crashing with anemonedock.dylib

Here is the new crash reports link:
https://www.dropbox.com/sh/v6zt85fo86eacs0/AAApumr0Zi0cerN9hAP9mLIAa?dl=0
