### ISSUE TITLE
Updating themes for iPad Pro

### ISSUE THREAD

**Issue by ghost** [AnemoneTeam/Anemone#66]
(I know what you're thinking... bear with me.)

So, the iPad Pro is out. Still no jailbreak for it. But... who's to say you can't future-proof Anemeone?

Simple proposition: add a note about the new iPad Pro icon size to the wiki. It's 167x167. Still uses the @2x suffix.

[Reference](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html).

**Comment by coolstar** [comment]
There's no need for adding the iPad Pro's size. Anemone supports using "-large" (autoscaling) with themes. If themes are using 180x180 or 226x226 icons, Anemone will autoscale the icons for the iPad Pro's 167x167. Themes do not need any adjustment.

**Comment by cj81499** [comment]
I think he is saying that the traditional IB method can't use theme icons yet, so if you want to support WB and Anemone, you can't.

**Comment by ghost** [comment]
Fair point, and since the Pro uses an odd-numbered icon size, it's unlikely the filenames will be the same.

However, down(scaling/sampling) icons is rather lazy and can lead to distorted images. [Apple's not setting a good example here...](http://www.paintcodeapp.com/news/iphone-6-screens-demystified)

**Comment by coolstar** [comment]
@cj81499 WinterBoard is offtopic
