### ISSUE TITLE
Activator Icon

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#68]
I mentioned this in the Slack chat, but figured I'd put it here as well.

The activator icon acts strangely. It used to be possible to theme it with a mixture of Bundles and IconBundles, but this seems to have stopped working. I suggest that whenever a theme that changes the icon of Activator is applied, you do [this fix](https://www.reddit.com/r/iOSthemes/comments/2rdwdp/me1_activator_icon0_how_to_theme_the_stubborn/) and then revert it when the theme is no longer applied.

**Comment by coolstar** [comment]
This should be possible to implement, albeit only for themes that theme icons via IconBundles. We'll take a look at it soon.

**Comment by cj81499** [comment]
Since I've completely switched to IconBundles, that sounds good to me!
