### ISSUE TITLE
Different Icons for each Folder

### ISSUE THREAD

**Issue by Marty-McFly73** [AnemoneTeam/Anemone#7]
Coolstar, first off - you are a genius my friend.  Thank you for Anemone.  I'm using v278 and trying to use different icons for each folder - not having much luck.  I'm using the naming convention as mentioned on Twitter....

ANEMFolderIconBG-<name>.png 

So just to confirm, if I have a folder called "Cydia", I need....

ANEMFolderIconBG-<Cydia>.png 
ANEMFolderIconBG-<Cydia>@2x.png

Do I have that right because that's what I've tried and just can't get it.  I can get the same icon for each folder working but not individual icons for each folder.  Thanks in advance for any help you can provide.

Marty Mcfly

**Comment by Marty-McFly73** [comment]
Forum edited my post so you can't see brackets.  Here is what I have.....

![new-1](https://cloud.githubusercontent.com/assets/13821911/9294485/8abff51e-441c-11e5-86ad-0b6e7169e37f.png)

**Comment by benklinger** [comment]
Hi Marty,

I think you should lose the brackets and just add ANEMFolderIconBG-Cydia.png

**Comment by Marty-McFly73** [comment]
Thanks for the reply bro.  Tried that....and all sorts of other naming possibilities lol.  No luck :(

**Comment by enaloha** [comment]
I can get the individual folders to show up (iPhone 6+, using the nomenclature as mentioned by benklinger above but with @3x icons). The problem I have is that I want to accomplish something like the attached image, but instead I get the proper folder icon as background with the mini icons on top. Is there a way to hide the mini icon grid?

The below was taken when CustomFolderIcons was still working and I'd like to replicate it:

![anemone](https://cloud.githubusercontent.com/assets/13284542/9323663/b813347e-451e-11e5-84bb-08e7ecd129bf.jpg)

**Comment by enaloha** [comment]
What I'm getting instead is this:

![anemone2](https://cloud.githubusercontent.com/assets/13284542/9323704/2e06b3d6-451f-11e5-8d6f-a55afd7f8eee.jpg)

**Comment by benklinger** [comment]
this is exactly the thing I want to do as well.

**Comment by cj81499** [comment]
I imagine the best way to implement this would be an option in an info.plist

**JUST AS AN IDEA FOR @coolstar (This isn't implemented so don't try it)**

EDIT: The text wasn't showing up how I wanted so: http://pastebin.com/7fs2MLPg

That would make all folders except Games show their icons.

**Comment by Marty-McFly73** [comment]
Got everything working perfectly...

![img_0018](https://cloud.githubusercontent.com/assets/13821911/9621731/6464e5a8-50f8-11e5-8a06-037c42866ff3.PNG)

So, in the end, the key for me was having a blank ANEMFolderIconBG@2x.png file AS WELL as the individual folder icon files...

![img_0019](https://cloud.githubusercontent.com/assets/13821911/9621735/7007635e-50f8-11e5-9bd1-c48d6ddeaf4b.PNG)

**Comment by enaloha** [comment]
Yes, everything is working. The problem really is to hide the icon matrix. Thankfully there is a tweak that will do that while we wait for Anemone to implement that via the info.plist. The tweak to work around the matrix is called NoMiniIconGrid.

**Comment by Marty-McFly73** [comment]
Oh ya, by the way guys - tweak called "NoMiniIconGrid" will remove those mini icons you see.  Hope that helps.

**Comment by coolstar** [comment]
FolderGridImageAlpha has been added so you can use that key in your theme's Info.plist to change the opacity of the icon grid inside the folder icon.
