### ISSUE TITLE
Takes Long To Open Certain Categories 

### ISSUE THREAD

**Issue by nknight0** [AnemoneTeam/Anemone#70]
When I enter Anemone to change a theme, sometimes it refuses to open certain categories, such miscellaneous, anemone, classic dock etc. I have reinstalled it, use I cleaner to clean my device, rebooted my device. Why does it do this and how can I fix it.

iPod 5g on iOS 8.4

**Comment by coolstar** [comment]
Does this issue still happen on the latest nightly? Also, what do you mean by "refuses to open categories"?

**Comment by coolstar** [comment]
Closing due to no response for 3 months.
