### ISSUE TITLE
Settings App Crashing! Please fix

### ISSUE THREAD

**Issue by Grenades** [AnemoneTeam/Anemone#71]
My settings app has been crashing for weeks due to AnemoneUIKit.dylib I haven't been able to access settings unless I boot into safe mode or completely disable AnemoneUIKit.dylib i've tested everything and it's definitely anemone causing it. I've been waiting patiently for a fix but it's been so long!

**Comment by Grenades** [comment]
iPhone 6, 8.4

**Comment by coolstar** [comment]
Does this issue still happen with the latest version from the fast ring repo?

**Comment by Grenades** [comment]
Yes, but I found out that I had no problems after disabling "Muze"

**Comment by coolstar** [comment]
Looks like the issue is with the theme "Muze"

**Comment by gmawji** [comment]
I know this is closed but I thought I'd shed some light on this. Any theme with the old IconCache.artwork inside the com.apple.preferences folder will crash the settings app. This was discovered ages ago so it's just a case of the theme not being updated.
