### ISSUE TITLE
Classic Dock themes not working

### ISSUE THREAD

**Issue by MikeyScene420** [AnemoneTeam/Anemone#73]
Latest update won't theme the dock. Tested with iPhone 6 Plus on 9.0.2

**Comment by LaCh0uine** [comment]
Any news about this ?

**Comment by coolstar** [comment]
Modern mode docks still work fine. Classic mode dock themes seem to be having issues. We are investigating the cause of this bug.

**Comment by LaCh0uine** [comment]
@coolstar Is it easy to convert classicdock to modern ?

**Comment by coolstar** [comment]
@LaCh0uine yes, it is

**Comment by coolstar** [comment]
Fixed in 1.1-138.
