### ISSUE TITLE
Safe mode after instalation respring

### ISSUE THREAD

**Issue by camper1x** [AnemoneTeam/Anemone#75]
Hi Guys,
i just want to switch from Winterboard to Anemone and got ugly bug.
After installing from BigBoss repo i made a respring and after it phone immediately goes to safe mode (apple logo -> lockscreen for 3sec -> safe mode). Tried cleaning all anemone data, but still nothing....

I'm on 8.4 on iPhone 6 Plus.

**Comment by In5pired0ne** [comment]
try going to icleaner pro while in Safemode and cut off AnemoneDock.dylib then respring and see if thats works.

**Comment by camper1x** [comment]
Working like charm! thanks a lot. I don't even think about it.

**Comment by In5pired0ne** [comment]
no problem
