### ISSUE TITLE
Settings app crash

### ISSUE THREAD

**Issue by pigeon-man** [AnemoneTeam/Anemone#76]
Since the latest update, while I have classic dock running I can not open the iOS settings app without it instantly crashing. Crashreporter logs "preferences" as what crashed, "preferenceloader.dylib" as the main suspect and anemone as another suspect. This stops if I disable all settings in classic dock.

**Comment by pigeon-man** [comment]
The "anemoneUIkit.dylib" is the other suspect

**Comment by coolstar** [comment]
Does this still happen on the latest Anemone fast ring build?

**Comment by coolstar** [comment]
Issue hasn't been updated since December. Probably fixed.
