### ISSUE TITLE
[Request] Anemone Effects

### ISSUE THREAD

**Issue by Pois0nDF** [AnemoneTeam/Anemone#78]
Would it be possible to add a per page Anemone Effects. The idea would be to allow individual Anemone Effects per page. Iconoclasm has this option with layouts,not sure if its possible with effects

**Comment by coolstar** [comment]
Anemone Icon Effects can't work on a per-page basis. Anemone Icon Effects work across all icons on the device. The only distinction we can make for Icon Effects is whether the icon is being rendered in an app/SpringBoard or which app it's being rendered in. Furthermore, we would have to account for icons being moved from one page to another in edit mode. Such functionality is way out of scope for a general purpose theming utility.
