### ISSUE TITLE
HTML Wallpapers

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#79]
Implement per-page HTML that shows in SpringBoard. Use WKWebView in iOS 8 & 9 to keep the HTML wallpapers out of the SpringBoard process for stability and security reasons. Also implement a javascript API for wallpapers to be able to access settings/other features through Anemone while still maintaining the user's security and privacy.
- [x] Use WKWebView to load HTML Wallpaper
- [x] Implement File Read APIs
- [x] Test File Read against images
- [x] Implement URL Read APIs
- [x] Implement Console Debug APIs
- [x] Implement File Write APIs
- [ ] Implement Timer APIs (Might not be needed)
- [ ] Implement Network Connectivity Status APIs (WiFi/Cellular/Airplane Mode)
- [ ] Implement Battery Status APIs (Percentage/Is Charging)

**Comment by coolstar** [comment]
This is now currently in progress. See: https://github.com/AnemoneTeam/Anemone/wiki/HTML-Support

Further discussion will be on the Anemone slack.

**Comment by Nelnamara** [comment]
Old topic it seems but is per page HTML possible in the 2.0 versions with Electra?  I have 5 themes I am updating for 11 / new device support and was curious about this.  I have a theme that screams for per page setups.

I checked the wiki but here is the only place I could find a reference :)
