### ISSUE TITLE
AnemoneDock.dylib causes crashes

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#8]
I think it may be an issue with my iPhone 6, because it works on my iPod 5, but when I have AnemoneDock.dylib enabled in iCleaner, my springboard keeps crashing into safe mode so I can't theme the Dock on my phone.

**Comment by coolstar** [comment]
Can you send a crash report with the crash log and syslog?

**Comment by cj81499** [comment]
It's not happening anymore, but I know AnemoneDock.dylib caused it because when I disabled it in iCleaner, the crashed stopped. If it starts again, I'll post it here.

**Comment by cj81499** [comment]
Alright, it happened again.

[Crash Log](http://pastebin.com/rgXpnvtu)

[Syslog](http://pastebin.com/nz075uz5)

**Comment by coolstar** [comment]
It doesn't look like it's AnemoneDock causing it. Must be some other tweak.

**Comment by cj81499** [comment]
How strange. I haven't had another crash since then so it's probably fine. Any idea what the other tweak was?

**Comment by coolstar** [comment]
No. Anyways, looks like AnemoneDock isn't causing the crash so the issue is being closed.
