### ISSUE TITLE
Share Sheet IconBundles / AnemoneEffects sizing

### ISSUE THREAD

**Issue by coolstar** [AnemoneTeam/Anemone#80]
From @dreamnet:

Some strange things are happening in the share sheet, I tryed to use a 50% opaque magenta image in various ways, here is the result:
![image](https://cloud.githubusercontent.com/assets/1431548/12180505/d0781a06-b531-11e5-8cfe-03098d0e62d5.png)

The Message icon is themed with IconBundles, using Anemones -large method (IconBundles/com.apple.MobileSMS-large.png, 180x180px).
The Mail icon ist themed with iconBundles, using @2x (IconBundles/com.apple.mobilemail@2x.png, 120x120px).
The Save PDF to iBooks icon ist themed with the Bundles method (Bundles/com.apple.iBooks/AppIcon60x60@2x.png, 120x120px).
The Facebook icon is themed with the Bundles method (Bundles/com.apple.share.Facebook.post/SLFacebookActivity@2x~iphone.png, 120x120px).
Message and Mail icon are shown with 124x124px (without mask), Save PDF to iBooks and Facebook icos are shown with 120x120px (with mask). The last two are also darker than the first two. For the first three icons the background from AnemoneEffects is used, for the fourth - not. I am also wondering, why the icon for Notes is not themed - it is themed in Springboard, using the IconBundles method (-large).

**Comment by dreamnet** [comment]
@coolstar Thanks for opening the issue and checking! :+1:

**Comment by coolstar** [comment]
@dreamnet can you send me the theme files you used to get this issue? I can take a look at this today

**Comment by dreamnet** [comment]
@coolstar Here it is: [ShareSheet Test.theme.zip](https://github.com/AnemoneTeam/Anemone/files/138674/ShareSheet.Test.theme.zip)

**Comment by coolstar** [comment]
@dreamnet is this issue still relevant now that #100 was implemented?

**Comment by dreamnet** [comment]
@coolstar No, I think it's fine now.

**Comment by coolstar** [comment]
Alright. Awesome
