### ISSUE TITLE
Weird dock in iPhone 6 Plus with Anemone 1.1.80 and 0xygen iOS9 Anemone theme installed.

### ISSUE THREAD

**Issue by jmblazquezh** [AnemoneTeam/Anemone#87]
Hello.
I send you the same bug I reported to developers of 0xygen iOS9 Anemone theme, because I don´t now in which app is the bug:

"Hello and good afternoon.

I have a weird dock whis this theme installed. I explain to you.

In screenshot annexed named IMG_0256.jpg you can see my homescreen with no type of dock selected in anemone. As you see, there's a dock in black color as default color, very weird dock with no blurred efects as default dock in iOS9.

In screenshot annexed named IMG_0257.jpg you can see option 0xygen iOS9 Dock white selected inside Anemone app. Then I respring and as you can see, the result is what you can see in screenshot annexed named IMG_0258.jpg. The 0xygen iOS9 Dock white appears in light gray color, because the weird dock in black color described in the previous paragraph still is here.

In screenshot annexed named IMG_0259.jpg you can see list of tweaks I have installed in my iPhone 6 Plus. What could be the cause of this strange dock in black color displayed by default ?. I changed the wallpaper by another to see if this is the problem, but that strange dock in black color persists.

Greetings from Spain."

![img_0256](https://cloud.githubusercontent.com/assets/17223799/13029896/04ee8b1a-d299-11e5-8390-9ea1e5e789a3.jpg)
![img_0257](https://cloud.githubusercontent.com/assets/17223799/13029898/04fce570-d299-11e5-81bb-761540063eac.jpg)
![img_0258](https://cloud.githubusercontent.com/assets/17223799/13029899/0502096a-d299-11e5-90be-7816424a1265.jpg)
![img_0259](https://cloud.githubusercontent.com/assets/17223799/13029897/04f6b52e-d299-11e5-853b-5f2eec5c65fa.jpg)

**Comment by coolstar** [comment]
This is a problem with Eclipse, not with Anemone.

**Comment by jmblazquezh** [comment]
OK. I'd reported to Eclipse3 Developer.

Thanks.
