### ISSUE TITLE
Performance Problem

### ISSUE THREAD

**Issue by mofde2003** [AnemoneTeam/Anemone#90]
Hey, after the Updats 1.1.65 and 1.1.66 is my system verry Slow. I have change to Winterboard and i can see my system i fast. How is my Problem with Anemone? I have clean The old files with iClean and have Anemone new install. The Problem activ. Bye Anemone to The next Update and Hello Winterboard after Release Anemone. Can you help me?

**Comment by coolstar** [comment]
Insufficient details provided.
