### ISSUE TITLE
Anemone Crash on ios 7.1.1 

### ISSUE THREAD

**Issue by nghiaagent** [AnemoneTeam/Anemone#91]
The error is.. self-explanatory. Whenever I launch the app on my iPad Air, it crashes. There's no trace in CrashReporter, so there's no log I can send to you guys

**Comment by FormerMe** [comment]
Same here on iPhone 5s.

**Comment by coolstar** [comment]
How many themes do you have installed?

**Comment by nghiaagent** [comment]
Back then, I had Ace El Cap.

**Comment by nghiaagent** [comment]
Back then, I had Ace El Cap.

**Comment by nghiaagent** [comment]
Back then, I had Ace El Cap.

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

Here should be the syslog

Fri Mar 18 02:25:31 2016: Anemone (com.apple.console): MS:Notice: Injecting: com.anemonetheming.anemone [Anemone](847.26)
Fri Mar 18 02:25:32 2016: Anemone (com.apple.console): MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/AnemoneColors.dylib
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneColors: ColorOverride.xm:226] ERROR: logos: message not found [UIColor tableViewBackgroundColorOpaque]
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneColors: TintColors.xm:187] ERROR: logos: nil class FluidProgressView
Fri Mar 18 02:25:32 2016: Anemone (com.apple.console): MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/AnemoneCore.dylib
Fri Mar 18 02:25:32 2016: Anemone (com.apple.console): MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/AnemoneIcons.dylib
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: IconBundles.xm:160] ERROR: logos: nil class SBIconImageCrossfadeView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: IconBundles.xm:160] ERROR: logos: message not found [UIImage _applicationIconImageForBundleIdentifier:roleIdentifier:format:scale:]
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: IconLabels.xm:163] ERROR: logos: nil class SBIconLabelImage
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: IconLabels.xm:163] ERROR: logos: nil class SBIconLabelImage
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: FolderIcons.xm:226] ERROR: logos: nil class SBFolderIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: FolderIcons.xm:226] ERROR: logos: nil class SBFolderIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: FolderIcons.xm:226] ERROR: logos: nil class SBFolderIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: FolderIcons.xm:226] ERROR: logos: nil class SBFolderIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [AnemoneIcons: FolderIcons.xm:226] ERROR: logos: nil class SBFolderIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.apple.console): MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/AnemoneUIKit.dylib
Fri Mar 18 02:25:32 2016: Anemone (com.apple.console): MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/libstatusbar.dylib
Fri Mar 18 02:25:32 2016: Anemone (user): CoreFoundation = 847.260000
Fri Mar 18 02:25:32 2016: Anemone (com.apple.console): MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/z_AnemoneIconEffects.dylib
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconEffects.xm:212] ERROR: logos: nil class _UIUserDefaultsActivity
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconEffects.xm:212] ERROR: logos: nil class UIApplicationExtensionActivity
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconEffects.xm:212] ERROR: logos: nil class PUPublishingActivity
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconEffects.xm:212] ERROR: logos: nil class PUAirplayActivity
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconEffects.xm:212] ERROR: logos: nil class PUAlbumStreamActivity
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconEffects.xm:212] ERROR: logos: nil class SBNewsstandIcon
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconEffects.xm:212] ERROR: logos: nil class SBClockApplicationIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconShadows.xm:90] ERROR: logos: nil class SBIconView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconShadows.xm:90] ERROR: logos: nil class SBIconView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [z_AnemoneIconEffects: IconShadows.xm:90] ERROR: logos: nil class SBIconView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [Anemone: Badges.xm:135] ERROR: logos: nil class SBIconBadgeView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [Anemone: Badges.xm:135] ERROR: logos: nil class SBIconBadgeView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [Anemone: Clock.xm:94] ERROR: logos: nil class SBClockApplicationIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [Anemone: Clock.xm:94] ERROR: logos: nil class SBClockApplicationIconImageView
Fri Mar 18 02:25:32 2016: Anemone (com.anemonetheming.anemone): [Anemone: Calendar.xm:224] ERROR: logos: nil class SBLockScreenViewController
Fri Mar 18 02:25:32 2016: Anemone (user): GSRegisterPurpleNamedPort Couldn't register com.anemonetheming.anemone with the bootstrap server. Error: unknown error code (1100).
This generally means that another instance of this process was already running or is hung in the debugger.
Fri Mar 18 02:25:32 2016: ReportCrash (Crash Reporter): Saved crashreport to /Library/Logs/CrashReporter/stacks-2016-03-18-022532.ips using uid: 0 gid: 0, synthetic_euid: 0 egid: 0
Fri Mar 18 02:25:32 2016: ReportCrash (Crash Reporter): ReportCrash acting against PID 1520
Fri Mar 18 02:25:32 2016: ReportCrash (Crash Reporter): Formulating crash report for process Anemone[1520]
Fri Mar 18 02:25:32 2016: ReportCrash (Crash Reporter): Saved crashreport to /var/mobile/Library/Logs/CrashReporter/Anemone_2016-03-18-022532_iPad.ips using uid: 0 gid: 0, synthetic_euid: 501 egid: 0

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by nghiaagent** [comment]
So currently I have no theme installed, and according to the now-functional Crash Reporter, the only libraries loaded other than Anemone is librocketbootstrap.dylib and libstatusbar.dylib

**Comment by coolstar** [comment]
It seems to be a bug in iOS 7.1.x and uicache. Reboot your device and the Anemone app will work.

**Comment by leepattison** [comment]
Every update since 1.1-80 crashes on trying open Anemone on my spare ip 4 and ip 5 both on  iOS7.1.2, 1.1-80 works fine on both devices.
Anybody struggling to get Anemone to work just find an older deb Version (1.1-80) which always works.

**Comment by coolstar** [comment]
Fixed in build 273 on the fast ring repo.
