### ISSUE TITLE
Badges floating above app icon

### ISSUE THREAD

**Issue by vonklebow** [AnemoneTeam/Anemone#94]
badges stay floating way above the app icon only on the home screen, mainly the dock but others have been floating on the home screen. I have to lock screen and reopen to refresh the home screen to have them come back down to earth.

**Comment by cj81499** [comment]
I'm not a developer, but your description is kinda hard to explain. Is there any way to show us what this looks like compared to what it should look like?

**Comment by vonklebow** [comment]
![image1](https://cloud.githubusercontent.com/assets/18490380/15005063/4483408a-1174-11e6-8b3a-489a72c21a00.PNG)

**Comment by vonklebow** [comment]
Hope that helps, mainly happens on the dock.  occasionally on other apps within the home screen.  in order to fix tis i have to enter the app or settings as you see below and exit to get back to normal.

**Comment by coolstar** [comment]
it looks like you have some tweaks modifying the dock. Which ones do you have installed?

**Comment by vonklebow** [comment]
springtomizer

**Comment by coolstar** [comment]
can you run "dpkg-query -l > list.txt" in a terminal and paste the contents of list.txt?

**Comment by vonklebow** [comment]
Just uninstalled terminal, let me re-install.

**Comment by vonklebow** [comment]
![image1-2](https://cloud.githubusercontent.com/assets/18490380/15005363/6ece4d40-1178-11e6-8d66-c899d51957e8.PNG)

**Comment by vonklebow** [comment]
Not sure exactly what I'm doing wrong

**Comment by coolstar** [comment]
you need lowercase L, not the | separator

**Comment by vonklebow** [comment]
Just comes back with my phone name and command prompt again, I even attempted it in su mode same thing. I ran this with the spaces between query and (minus/dash) and the spaces. 

Is there a log I am supposed to grab? 

dpkg-query -l > list.txt

**Comment by vonklebow** [comment]
found it in mobile, via ifile

**Comment by vonklebow** [comment]
What am I looking for?

**Comment by vonklebow** [comment]
I have the list.txt file, is there anything in particular that should pop out at me?

**Comment by coolstar** [comment]
upload it to ghostbin and link it here please

**Comment by vonklebow** [comment]
https://ghostbin.com/paste/grant/598s4e9kv2opnx2ajrpvb937o4ouyzz2/accept

**Comment by vonklebow** [comment]
https://ghostbin.com/paste/3tfs9/raw

**Comment by vonklebow** [comment]
This only started happening after the Anemone install and springtomize.  Could be that app as well, going to start a thread on that app too.

**Comment by vonklebow** [comment]
Update: i unchecked "cover flow" in sprintomize and it stopped. Looks like the bending of the dock created the issue. Its not Anemone, thanks for all your support. Reporting to springtomize.
