### ISSUE TITLE
Anemone crashing springboard

### ISSUE THREAD

**Issue by lupetta57** [AnemoneTeam/Anemone#95]
i have iphone 6S ios 9.1. i love Anemone but i don't can use .......... after jailbreak i have installed Anemone (first installation on Cydia). 
right after I installed Springtomize (this installation includes springtomize and preferenceloader).
and 'it was the end !! I had to uninstall anemone because  was a continuous crash. now i have winterboard ...
help me ....

**Comment by coolstar** [comment]
This sounds like a problem with Springtomize, not Anemone.

**Comment by lupetta57** [comment]
ok, but i have Springtomize and i like it!! but I also want anemone. 
now i have disableb two addon (anemone) of cydia Substrate and my iphone have anemone+springtomize without crash!
![img_3973](https://cloud.githubusercontent.com/assets/19707113/16086637/8c324ad4-3320-11e6-9578-35de2ade5b1c.jpg)

what do you think about it?
did I do something wrong?
