### ISSUE TITLE
Aliases for theme resources

### ISSUE THREAD

**Issue by Shugabuga** [AnemoneTeam/Anemone#96]
Is there a way to share resources (i.e. use the same glyphs in different apps) to make the theme size smaller? I am working on a theme that uses the same resources dozens of times, and this could really help make the theme smaller.

**Comment by coolstar** [comment]
You may use symlinks to have a file point to another file rather than duplicating the glyph.

**Comment by Shugabuga** [comment]
The symlink be pointing to the file in the .theme bundle, right?

**Comment by coolstar** [comment]
yes
