### ISSUE TITLE
Unsupported apps square shapes

### ISSUE THREAD

**Issue by jailbreaker98** [AnemoneTeam/Anemone#97]
When I set a team op anemone the supported apps look fine but all the unsupported apps are big squares and look really ugly. Anyone else who has this problem and does anyone have solutions? I re-installed all themes and anemone itself but that didn't work...

**Comment by coolstar** [comment]
the theme you have installed might be disabling or changing the icon mask. This is a theme issue, and not an issue with Anemone itself.
